"use client";

import React, { useState, useRef } from "react";
import { createClient } from "@/lib/supabase/client";
import { useRouter } from "next/navigation";

type Props = {
  userId: string;
};

export default function GymRegistrationForm({ userId }: Props) {
  const supabaseRef = useRef(createClient());
  const supabase = supabaseRef.current;
  const router = useRouter();

  const [gymName, setGymName] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleCreate = async () => {
    const name = gymName.trim();
    if (!name) return;
    setLoading(true);
    setError(null);

    // Create gym (invite_code auto-generated by DB default)
    const { data: gym, error: gymError } = await supabase
      .from("gyms")
      .insert({
        owner_id: userId,
        name,
        is_active: false,
      })
      .select()
      .single();

    if (gymError || !gym) {
      setError("Failed to create gym. Please try again.");
      setLoading(false);
      return;
    }

    // Mark user as gym owner
    await supabase
      .from("profiles")
      .update({ is_gym_owner: true })
      .eq("id", userId);

    router.refresh();
  };

  return (
    <div className="max-w-md mx-auto">
      <div className="bg-zinc-900 border border-white/10 rounded-2xl p-6 text-center">
        <div className="text-5xl mb-4">🏫</div>
        <h3 className="text-lg font-bold text-white mb-2">Register your gym</h3>
        <p className="text-sm text-gray-400 mb-6">
          It's free to get started. Create your gym, get your invite QR code, and start tracking your students.
        </p>

        <input
          type="text"
          placeholder="Gym name (e.g. Gracie Academy Tokyo)"
          value={gymName}
          onChange={(e) => setGymName(e.target.value)}
          onKeyDown={(e) => { if (e.key === "Enter" && gymName.trim()) handleCreate(); }}
          className="w-full bg-zinc-800 border border-white/10 rounded-xl px-4 py-3 text-sm text-white placeholder-gray-500 mb-4 focus:outline-none focus:border-[#e94560]/60"
          maxLength={80}
          aria-label="Gym name"
        />

        <button
          onClick={handleCreate}
          disabled={loading || !gymName.trim()}
          className="w-full bg-[#e94560] hover:bg-[#c73652] disabled:opacity-50 text-white font-semibold py-3 rounded-xl transition-colors"
          aria-label="Create gym"
        >
          {loading ? "Creating..." : "Create gym (free)"}
        </button>

        {error && <p className="text-red-400 text-xs mt-3">{error}</p>}

        <p className="text-[10px] text-gray-600 mt-4">
          No credit card required to start. Upgrade to Gym Pro ($49/mo) to unlock churn alerts and curriculum broadcasts.
        </p>
      </div>
    </div>
  );
}
