/**
 * lib/bjjTechniques.ts
 *
 * Static list of common BJJ technique names for autocomplete suggestions.
 * Used in TechniqueLogForm to help white/blue belts name techniques correctly.
 * Covers submissions, sweeps, guard passes, takedowns, escapes, and positions.
 */

export const BJJ_TECHNIQUE_SUGGESTIONS: string[] = [
  // ── Submissions ─────────────────────────────────────────────────────────────
  "Armbar",
  "Triangle Choke",
  "Rear Naked Choke",
  "Guillotine Choke",
  "Kimura",
  "Americana",
  "Omoplata",
  "D'Arce Choke",
  "Anaconda Choke",
  "North-South Choke",
  "Bow and Arrow Choke",
  "Loop Choke",
  "Baseball Bat Choke",
  "Cross Collar Choke",
  "Ezekiel Choke",
  "Arm Triangle",
  "Von Flue Choke",
  "Clock Choke",
  "Twister",
  "Heel Hook",
  "Inside Heel Hook",
  "Outside Heel Hook",
  "Ankle Lock",
  "Straight Ankle Lock",
  "Toe Hold",
  "Kneebar",
  "Calf Slicer",
  "Wrist Lock",
  "Gogoplata",
  "Rubber Guard",
  "Brabo Choke",
  // ── Guard Sweeps ─────────────────────────────────────────────────────────────
  "Scissor Sweep",
  "Hip Bump Sweep",
  "Flower Sweep",
  "Pendulum Sweep",
  "Elevator Sweep",
  "Sit-Up Sweep",
  "Butterfly Sweep",
  "Sickle Sweep",
  "Tripod Sweep",
  "Tomoe Nage",
  "Overhead Sweep",
  "X-Guard Sweep",
  "De La Riva Sweep",
  "Single Leg X Sweep",
  "Berimbolo",
  "Back Roll Sweep",
  // ── Guard Passes ─────────────────────────────────────────────────────────────
  "Knee Slice Pass",
  "Torreando Pass",
  "Double Under Pass",
  "Over-Under Pass",
  "Stack Pass",
  "Leg Drag Pass",
  "X-Pass",
  "Smash Pass",
  "Headquarters Pass",
  "Pressure Pass",
  "Long Step Pass",
  "Estima Lock to Pass",
  "Bullfighter Pass",
  "Cartwheel Pass",
  // ── Takedowns / Trips ────────────────────────────────────────────────────────
  "Single Leg Takedown",
  "Double Leg Takedown",
  "Hip Throw (Ogoshi)",
  "Foot Sweep",
  "Sacrifice Throw",
  "Kouchi Gari",
  "Ouchi Gari",
  "Tai Otoshi",
  "Uchi Mata",
  "Seoi Nage",
  // ── Escapes ──────────────────────────────────────────────────────────────────
  "Upa Bridge Escape",
  "Elbow-Knee Escape",
  "Turtle Recovery",
  "Back Escape",
  "Side Control Escape",
  "Mount Escape",
  "Guard Recovery",
  "Standing Guard Break",
  // ── Positions / Controls ──────────────────────────────────────────────────────
  "Closed Guard",
  "Half Guard",
  "Z-Guard",
  "Butterfly Guard",
  "Spider Guard",
  "Lasso Guard",
  "De La Riva Guard",
  "Reverse De La Riva",
  "Single Leg X",
  "X-Guard",
  "Worm Guard",
  "93 Guard",
  "Mount",
  "Back Control",
  "Side Control",
  "North-South",
  "Knee on Belly",
  "Turtle",
  "Headquarters",
  "Quarter Guard",
];
