#!/usr/bin/env python3
"""
Batch 1 PT translation: nav, dashboard, beltProgress, training, techniques, techniquesPage
Outputs /tmp/pt_batch1.json with Brazilian Portuguese translations.
"""

import json

TRANSLATIONS = {
    "nav.records": "Registros",
    "nav.mypage": "Minha Página",
    "dashboard.welcomeBack": "Bem-vindo de volta, {name} 🙌",
    "dashboard.weekTraining": "Esta Semana",
    "dashboard.techniques": "Técnicas",
    "dashboard.streakMsg0": "Comece a registrar seu treino hoje!",
    "dashboard.streakMsg1": "Continue treinando!",
    "dashboard.streakMsg3": "🎯 {n} dias seguidos! Ótimo hábito se formando.",
    "dashboard.streakMsg7": "⚡ {n} dias seguidos! Você está pegando fogo!",
    "dashboard.streakMsg14": "💪 {n} dias seguidos! Ritmo incrível.",
    "dashboard.streakMsg30": "🔥 {n} dias seguidos! Consistência imparável!",
    "dashboard.intensityHard": "Intensidade alta",
    "dashboard.intensityModerate": "Intensidade moderada",
    "dashboard.intensityLight": "Treino leve",
    "dashboard.intensityGettingStarted": "Começando",
    "dashboard.streakCardUnstoppable": "🔥 Imparável",
    "dashboard.motivationTrainedToday": "Ótimo treino hoje! Continue com esse ritmo 🔥",
    "dashboard.motivationTrainedYesterday": "Ótima sessão ontem! Pronto para treinar hoje?",
    "dashboard.motivationGapDays": "{n} dias desde sua última sessão. Mais uma nesta semana — consistência é força.",
    "dashboard.motivationGapWeek": "O tatame está te esperando. Volte e role!",
    "dashboard.motivationGapLong": "Já faz um tempo — vamos voltar para o tatame!",
    "dashboard.inviteTitle": "Convide Seus Parceiros de Treino",
    "dashboard.inviteDesc": "Treinem juntos, acompanhem juntos. Compartilhe o BJJ App com sua equipe.",
    "dashboard.inviteCta": "Compartilhar Link de Convite",
    "dashboard.emptyStateNewToBjj": "Novo no BJJ?",
    "dashboard.emptyStateWikiLink": "Comece aqui: Fundamentos do White Belt →",
    "dashboard.defaultAthleteName": "Atleta",
    "dashboard.defaultCoachName": "Professor",
    "dashboard.beltWhite": "White Belt",
    "dashboard.beltBlue": "Blue Belt",
    "dashboard.beltPurple": "Purple Belt",
    "dashboard.beltBrown": "Brown Belt",
    "dashboard.beltBlack": "Black Belt",
    "dashboard.loggedUnit": "registrado",
    "dashboard.bentoOnPaceFor": "· no ritmo para {n}",
    "dashboard.bentoAvgSession": "Média por Sessão",
    "dashboard.typeBreakdownTitle": "Foco deste Mês",
    "dashboard.typeOther": "Outros",
    "dashboard.bentoMinPerSession": "min / sessão",
    "dashboard.upsellWinRateLabel": "📈 Gráfico de Treino de 12 Meses",
    "dashboard.upsellInjuryLabel": "🩹 Gestão Corporal",
    "dashboard.upsellGraphDesc": "Veja seu volume de treino em 12 meses com gráficos detalhados.",
    "dashboard.upsellBodyDesc": "Acompanhe lesões e dores para treinar de forma mais inteligente.",
    "dashboard.upsellUpgradeCta": "Upgrade para Pro",
    "dashboard.sectionLog": "Registro",
    "dashboard.sectionToday": "Hoje",
    "dashboard.sectionYourGym": "Sua Academia",
    "dashboard.weeklyGoalReached": "Meta semanal alcançada!",
    "dashboard.weeklyGoalDone": "Meta: {done} · Feito: {count}",
    "dashboard.weeklyMoreSessions": "{n} sessão a mais para atingir sua meta semanal",
    "dashboard.weeklyMoreSessionsPlural": "{n} sessões a mais para atingir sua meta semanal",
    "dashboard.weeklyProgressLabel": "{done}/{goal} feito · {days}d restantes",
    "dashboard.weeklyOnPace": " ✓ no ritmo",
    "dashboard.weeklyPickUpPace": " ⚠ acelere o ritmo",
    "beltProgress.bjjHistory": "Histórico de BJJ",
    "beltProgress.timeAtBelt": "{belt}",
    "beltProgress.historyTitle": "Histórico de Promoções",
    "beltProgress.addPromotion": "Adicionar promoção",
    "beltProgress.savePromotion": "Salvar",
    "beltProgress.editHistory": "Editar",
    "beltProgress.noHistory": "Nenhum histórico de promoção ainda. Adicione suas faixas anteriores com \"Adicionar promoção\".",
    "training.title": "Registro de Treino",
    "training.add": "+ Adicionar Sessão",
    "training.update": "Atualizar",
    "training.durationUnit": "min",
    "training.typeShort": "Tipo",
    "training.instructorPlaceholder": "ex. Professor João",
    "training.partnerTag": "Parceiro de Sparring (opcional)",
    "training.partnerTagPlaceholder": "usuário",
    "training.memo": "Notas",
    "training.memoOptional": "Notas (opcional)",
    "training.memoPlaceholder": "Pontos principais, aprendizados da sessão de hoje...",
    "training.memoFormPlaceholder": "Insights, dicas, o que você aprendeu...",
    "training.backToToday": "Voltar para Hoje",
    "training.customMinutes": "Minutos personalizados",
    "training.all": "Todos",
    "training.calendarGi": "Gi",
    "training.calendarNogi": "NoGi",
    "training.calendarDrill": "Drill",
    "training.calendarComp": "Comp",
    "training.calendarOpen": "Open",
    "training.calendarTapToLog": "Toque para registrar uma sessão neste dia",
    "training.empty": "Seu tatame está vazio. Hora de treinar.",
    "training.emptyDesc": "Todo campeão começou com um rola.",
    "training.firstRecord": "+ Registrar Primeira Sessão",
    "training.noType": "Sem sessões deste tipo",
    "training.noMatch": "Nenhum registro corresponde a este filtro",
    "training.noMatchQuery": "Nenhum registro corresponde a \"{query}\"",
    "training.loadMore": "Carregar Mais",
    "training.loading": "Carregando...",
    "training.prev": "Anterior",
    "training.next": "Próximo",
    "training.collapse": "Recolher ▲",
    "training.showMore": "Mostrar Mais ▼",
    "training.printPDF": "Imprimir / Salvar como PDF",
    "training.dismissForToday": "Dispensar por hoje",
    "training.logSession": "Registre seu rola",
    "training.restoredDraft": "Sua sessão não salva foi restaurada. Por favor, salve-a.",
    "training.shareX": "Compartilhar no X",
    "training.edit": "Editar",
    "training.delete": "Excluir",
    "training.monthCount": "Este Mês",
    "training.monthTime": "Tempo este Mês",
    "training.loaded": "Carregado",
    "training.more": "Mais",
    "training.moreData": "→ Mais dados disponíveis. Clique em 'Carregar Mais'",
    "training.searchPlaceholder": "Buscar por notas ou técnica...",
    "training.saveFailed": "Falha ao salvar",
    "training.deleted": "Sessão excluída",
    "training.undo": "Desfazer",
    "training.deletedUndo": "Sessão excluída — toque em Desfazer para restaurar",
    "training.deleteFailed": "Falha ao excluir",
    "training.updated": "Sessão atualizada",
    "training.updateFailed": "Falha ao atualizar",
    "training.confirmDelete": "Excluir esta sessão?",
    "training.futureDate": "Não é possível registrar datas futuras",
    "training.durationRange": "A duração deve ser entre 1 e 480 minutos",
    "training.emptyFree": "✓ Gratuito",
    "training.emptyCloud": "✓ Sincronizado na nuvem",
    "training.emptyTrack": "✓ Acompanhe o progresso",
    "training.logNudgeTitle": "Registre a sessão de hoje!",
    "training.logNudgeSubtitle": "Toque para registrar um rola",
    "training.bentoTypeMix": "Mix de Tipos",
    "training.bentoSessions": "sessões",
    "training.periodLabel": "Período",
    "training.export": "Exportar",
    "training.linkCopied": "Link copiado",
    "training.copyLink": "Copiar link",
    "training.detailTitle": "Detalhe do Registro de Treino",
    "training.detailNotFound": "Registro não encontrado",
    "training.detailNotFoundDesc": "Este registro foi excluído ou você não tem permissão para visualizá-lo.",
    "training.backToRecords": "Voltar aos registros",
    "training.rollDetailsTitle": "Detalhes do Rola",
    "training.rollDetailsOptional": "opcional",
    "training.optionalToggle": "Detalhes opcionais",
    "training.optionalHint": "(professor · parceiro · peso)",
    "training.rollFocusLabel": "Foco",
    "training.partnerBeltLabel": "Faixa do Parceiro",
    "training.partnerSizeLabel": "Tamanho do Parceiro",
    "training.rollFocusFlow": "Flow",
    "training.rollFocusPositional": "Posicional",
    "training.rollFocusHard": "Rola Pesado",
    "training.rollFocusSurvival": "Sobrevivência",
    "training.partnerBeltWhite": "White",
    "training.partnerBeltBlue": "Blue",
    "training.partnerBeltPurple": "Purple",
    "training.partnerBeltBrown": "Brown",
    "training.partnerBeltBlack": "Black",
    "training.sizeDiffHeavier": "Mais pesado",
    "training.sizeDiffSimilar": "Similar",
    "training.sizeDiffLighter": "Mais leve",
    "training.durationCustom": "Personalizado",
    "training.periodAll": "Todo o Período",
    "training.periodMonth": "Este Mês",
    "training.periodWeek": "Esta Semana",
    "training.filterByDate": "Filtrar por Data",
    "training.weight": "Peso pós-treino (opcional)",
    "training.weightPlaceholder": "ex. 75.5",
    "training.freePlanNotice": "📋 Plano gratuito: mostrando últimos 30 dias",
    "training.upgradeFullHistory": "Upgrade para histórico completo →",
    "training.giName": "Qual Gi?",
    "training.giNamePlaceholder": "ex. Shoyoroll Comp Standard",
    "techniques.mastery1": "Conheço",
    "techniques.mastery2": "Praticando",
    "techniques.mastery3": "Consigo fazer",
    "techniques.mastery4": "Sou bom nisso",
    "techniques.mastery5": "Dominado",
    "techniques.masteryLevels.1": "Conheço",
    "techniques.masteryLevels.2": "Praticando",
    "techniques.masteryLevels.3": "Consigo fazer",
    "techniques.masteryLevels.4": "Sou bom nisso",
    "techniques.masteryLevels.5": "Dominado",
    "techniques.totalTechniques": "Técnicas",
    "techniques.favorites": "Favoritas",
    "techniques.categoryCount": "Categorias",
    "techniques.title": "Técnicas",
    "techniques.sortNewest": "Mais recente",
    "techniques.sortMasteryDesc": "Domínio ↓",
    "techniques.sortMasteryAsc": "Domínio ↑",
    "techniques.sortName": "Nome A-Z",
    "techniques.add": "+ Adicionar",
    "techniques.bulkAdd": "Adicionar em Lote",
    "techniques.bulkDesc": "Adicione várias técnicas de uma vez",
    "techniques.search": "Buscar técnicas...",
    "techniques.all": "Todas",
    "techniques.categories.guard": "Guard",
    "techniques.categories.passing": "Passing",
    "techniques.categories.submissions": "Submissions",
    "techniques.categories.takedowns": "Takedowns",
    "techniques.categories.escapes": "Escapes",
    "techniques.categories.back": "Back",
    "techniques.categories.mount": "Mount",
    "techniques.categories.other": "Outros",
    "techniques.name": "Nome",
    "techniques.namePlaceholder": "ex. Triangle Choke",
    "techniques.category": "Categoria",
    "techniques.mastery": "Domínio",
    "techniques.notes": "Notas",
    "techniques.notesPlaceholder": "Fonte, detalhes, dicas...",
    "techniques.save": "Salvar",
    "techniques.saving": "Salvando...",
    "techniques.cancel": "Cancelar",
    "techniques.bulkTitle": "Adicionar Técnicas em Lote",
    "techniques.nameMultiple": "Nomes (um por linha)",
    "techniques.nameMultiplePlaceholder": "Triangle Choke\nArmbar\nRear Naked Choke",
    "techniques.bulkCount": "{n} técnica(s)",
    "techniques.categoryMultiple": "Categoria (todas)",
    "techniques.masteryMultiple": "Domínio (todas)",
    "techniques.bulkSave": "Adicionar Técnicas",
    "techniques.loading": "Carregando...",
    "techniques.empty": "Nenhuma técnica ainda",
    "techniques.emptyDesc": "Adicione sua primeira técnica acima",
    "techniques.update": "Atualizar",
    "techniques.noResults": "Nenhuma técnica encontrada",
    "techniques.expand": "Expandir",
    "techniques.collapse": "Recolher",
    "techniques.edit": "Editar",
    "techniques.delete": "Excluir",
    "techniques.nameRequired": "Nome da técnica é obrigatório",
    "techniques.nameTooLong": "Nome muito longo (máx. 80 caracteres)",
    "techniques.duplicate": "'{name}' já existe",
    "techniques.duplicateBulk": "Duplicata encontrada: '{name}'",
    "techniques.bulkError": "Cada linha deve ser um nome de técnica (máx. 80 caracteres)",
    "techniques.nameTooLongBulk": "Nome muito longo: '{name}'",
    "techniques.bulkTooMany": "Muitas técnicas — por favor, insira 100 ou menos por lote",
    "techniques.allDuplicates": "Todas as técnicas já existem — nada novo para adicionar",
    "techniques.addedSingle": "Técnica adicionada!",
    "techniques.addedBulk": "{n} técnicas adicionadas!",
    "techniques.saveFailed": "Falha ao salvar",
    "techniques.addVideo": "+ Vídeo",
    "techniques.watchVideo": "Assistir",
    "techniques.editVideo": "Editar URL do vídeo",
    "techniques.removeVideo": "Remover vídeo",
    "techniques.confirmDelete": "Excluir esta técnica?",
    "techniques.deleted": "Técnica excluída",
    "techniques.deleteFailed": "Falha ao excluir",
    "techniques.updated": "Técnica atualizada",
    "techniques.updateFailed": "Falha ao atualizar",
    "techniques.addedToday": "Hoje",
    "techniques.addedYesterday": "Ontem",
    "techniques.addedDaysAgo": "{n} dias atrás",
    "techniques.addedWeekAgo": "1 semana atrás",
    "techniques.addedWeeksAgo": "{n} semanas atrás",
    "techniques.addedMonthAgo": "1 mês atrás",
    "techniques.addedMonthsAgo": "{n} meses atrás",
    "techniques.addedYearAgo": "1 ano atrás",
    "techniques.addedYearsAgo": "{n} anos atrás",
    "techniques.map": "Skill Map",
    "techniques.dangerBadge": "Avançado",
    "techniques.dangerTooltip": "Esta técnica tem maior risco de lesão. Pratique apenas sob supervisão qualificada.",
    "techniques.dangerConfirm": "⚠️ Esta é uma técnica avançada com maior risco de lesão (heel hooks, knee bars, neck cranks, etc.). Tem certeza que deseja adicioná-la? Sempre treine estas sob supervisão direta de um instrutor qualificado.",
    "techniques.tabJournal": "Diário",
    "techniques.tabSkillMap": "Skill Map",
    "techniques.tabWiki": "Wiki",
    "techniques.pin": "Fixar no topo",
    "techniques.unpin": "Desafixar",
    "techniques.pinned": "Fixada",
    "techniques.rustyTitle": "Técnicas Enferrujadas",
    "techniques.rustyCount": "{n} precisam de revisão",
    "techniques.rustyDesc": "Estas técnicas foram adicionadas há mais de 30 dias e ainda têm domínio baixo. Hora de treinar!",
    "techniques.rustyDays": "{n}d atrás",
    "techniques.rustyReview": "Revisar no Diário",
}

def main():
    # Read the source file to verify keys exist
    with open("/tmp/pt_missing_keys.json", "r", encoding="utf-8") as f:
        missing_keys = json.load(f)

    # Filter for only our target sections
    prefixes = ("nav.", "dashboard.", "beltProgress.", "training.", "techniques.", "techniquesPage.")
    filtered = {k: v for k, v in missing_keys.items() if k.startswith(prefixes)}

    # Verify we have translations for all filtered keys
    missing = [k for k in filtered if k not in TRANSLATIONS]
    if missing:
        print(f"WARNING: {len(missing)} keys not translated:")
        for k in missing:
            print(f"  {k}")

    # Output only keys that are in our target sections
    output = {k: v for k, v in TRANSLATIONS.items() if k in filtered}

    with open("/tmp/pt_batch1.json", "w", encoding="utf-8") as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    print(f"Written {len(output)} translations to /tmp/pt_batch1.json")


if __name__ == "__main__":
    main()
