#!/usr/bin/env python3
"""
Batch 3: Portuguese translations for BJJ App.
Sections: landing, gymLanding, gym, gymJoin, login, help, pro, pricing, proModal,
csv, report, achievement, extendedBadges, beltPromo, ageGate, install, onboarding,
guest, freeze, aiCoach, weightCut, wiki, skillmap.
"""

import json

TARGET_SECTIONS = {
    "landing", "gymLanding", "gym", "gymJoin", "login", "help", "pro",
    "pricing", "proModal", "csv", "report", "achievement", "extendedBadges",
    "beltPromo", "ageGate", "install", "onboarding", "guest", "freeze",
    "aiCoach", "weightCut", "wiki", "skillmap",
}

# Read the missing keys
with open("/tmp/pt_missing_keys.json", "r", encoding="utf-8") as f:
    all_keys = json.load(f)

# Filter for target sections
filtered_keys = {
    k: v for k, v in all_keys.items()
    if k.split(".")[0] in TARGET_SECTIONS
}

# For emoji keys, copy them directly from the source to avoid surrogate issues
# Build translations dict, preserving emojis from source where applicable.
translations = {
    # === guest ===
    "guest.banner": "Modo Visitante",
    "guest.signupLink": "Entrar no Tatame",
    "guest.saveToCloud": " para salvar seus dados na nuvem",
    "guest.welcome": "Bem-vindo! \ud83d\udc4b",
    "guest.noLogin": "Experimentar sem cadastro",
    "guest.sessions": "Sessões Registradas",
    "guest.totalMins": "Minutos Totais",
    "guest.ctaRecorded": "\ud83d\udcdd {n} sessões registradas!",
    "guest.ctaTitle": "Salvar seu progresso na nuvem?",
    "guest.ctaDesc": "Cadastre-se gratuitamente para sincronizar entre dispositivos, ver o calendário e acompanhar metas",
    "guest.ctaButton": "Entrar no Tatame \u2192",
    "guest.ctaNote": "\u203b Seus dados de visitante serão migrados automaticamente após o cadastro",
    "guest.migrated": "\ud83c\udf89 {n} sessão(ões) de visitante migrada(s) para sua conta!",

    # === login ===
    "login.github": "GitHub (para desenvolvedores)",
    "login.ageConfirm": "13 anos de idade ou mais",
    "login.ageConfirmNote": "(exigido por lei dos EUA)",
    "login.parentalConsent": "Idades entre 13\u201317 requerem consentimento dos pais ou responsável.",
    "login.disclaimerConfirm": "Eu entendo que o BJJ envolve risco físico e concordo em treinar de forma responsável. Não responsabilizarei o BJJ App por quaisquer lesões.",
    "login.checkboxesRequired": "\u2757 Por favor, marque ambas as caixas acima para continuar",
    "login.iabWarning": "Abrir no Safari ou Chrome",
    "login.iabDesc": "O login não é suportado nos navegadores integrados do Instagram / LINE / X. Por favor, copie a URL e abra no seu navegador padrão.",
    "login.iabCopy": "Copiar URL",
    "login.iabCopied": "\u2705 Copiado!",
    "login.ageConfirmPre": "Eu tenho",
    "login.disclaimerPre": "Eu entendo que",
    "login.disclaimerRisk": "o BJJ envolve risco físico",
    "login.disclaimerPost": "e concordo em treinar de forma responsável. Não responsabilizarei o BJJ App por quaisquer lesões.",
    "login.orEmail": "ou continue com email",
    "login.iabPaste": "Cole na barra de endereço do Safari ou Chrome para continuar",
    "login.errorCallback": "Erro no login. Por favor, tente novamente.",
    "login.errorDenied": "Acesso negado.",
    "login.errorGeneric": "Ocorreu um erro. Por favor, tente novamente.",
    "login.ariaAgeConfirm": "Confirmação de idade: Eu tenho 13 anos de idade ou mais",
    "login.ariaDisclaimerConfirm": "Aviso de treino: Eu entendo que o BJJ envolve risco físico",
    "login.ariaSignInGoogle": "Entrar com Google",
    "login.ariaEmailAddress": "Endereço de email",
    "login.ariaSendMagicLink": "Enviar link mágico de login",
    "login.ariaSignInGitHub": "Entrar com GitHub",

    # === help ===
    "help.title": "Ajuda e FAQ",
    "help.subtitle": "Perguntas frequentes sobre o BJJ App",
    "help.back": "Voltar ao Dashboard",
    "help.faq1Q": "Como registro uma sessão de treino?",
    "help.faq1A": "Toque no botão + no seu dashboard, selecione o tipo de treino (Gi, No-Gi, Drill, etc.), duração e observações. Sua sessão é salva instantaneamente.",
    "help.faq2Q": "Como funciona o contador de sequência?",
    "help.faq2A": "Sua sequência conta dias consecutivos com pelo menos uma sessão registrada. Treinos após meia-noite contam como o mesmo dia até 4h (data lógica de treino). Use o Streak Freeze (Pro) para proteger sua sequência em dias de descanso.",
    "help.faq3Q": "Posso mudar minha faixa?",
    "help.faq3A": "Sim! Vá em Perfil e toque na sua faixa para alterá-la. Se você for promovido, verá uma animação de celebração.",
    "help.faq4Q": "Como altero meu email ou nome de exibição?",
    "help.faq4A": "Vá em Perfil > Conta. Você pode alterar seu email (um link de confirmação será enviado) ou atualizar seu nome de exibição.",
    "help.faq5Q": "Como excluir minha conta?",
    "help.faq5A": "Vá em Perfil > Conta > Excluir Conta. Digite DELETE para confirmar. Todos os seus dados serão removidos permanentemente (conforme GDPR/CCPA).",
    "help.faq6Q": "O que é o Dashboard do Gym?",
    "help.faq6A": "O Dashboard do Gym permite que donos de academia acompanhem a atividade dos alunos, enviem currículo e reduzam a evasão. Alunos entram via QR code e podem controlar quais dados compartilham.",
    "help.faq7Q": "O que inclui o Pro?",
    "help.faq7A": "O Pro desbloqueia análises avançadas (gráficos de treino de 12 meses, gerenciamento corporal, streak freeze), skill maps de técnicas e suporte prioritário. $9,99/mês.",
    "help.faq8Q": "Como exporto meus dados?",
    "help.faq8A": "Vá em Perfil > Conta > Baixar meus dados (CSV). Todos os seus registros de treino serão exportados como arquivo CSV que você pode abrir em qualquer planilha.",
    "help.contactTitle": "Ainda precisa de ajuda?",
    "help.contactBtn": "Enviar Email ao Suporte",
    "help.faq9Q": "Minha sessão de treino não salvou?",
    "help.faq9A": "Verifique sua conexão de rede. As sessões são salvas no servidor quando online. Se o problema persistir, tente atualizar a página.",
    "help.faq10Q": "Como cancelo minha assinatura Pro?",
    "help.faq10A": "Vá em Perfil > Conta > Gerenciar Assinatura. Você pode cancelar com um clique. Os recursos Pro permanecem disponíveis até o final do período de cobrança.",
    "help.faq11Q": "Como exporto um relatório em PDF?",
    "help.faq11A": "Na página de Registros, clique no botão Exportar e selecione PDF. Um relatório com seu resumo de treino e estatísticas será gerado.",
    "help.faq12Q": "Não estou recebendo notificações",
    "help.faq12A": "Verifique as configurações de notificação do seu navegador. No iOS Safari, você precisa adicionar o app à Tela Inicial antes de ativar notificações.",
    "help.troubleshootingTitle": "Solução de Problemas",
    "help.troubleshootingSubtitle": "Problemas comuns e soluções",
    "help.faq13Q": "Posso exportar meus dados de treino?",
    "help.faq13A": "Sim! Você pode exportar todo o seu histórico de treino como CSV ou PDF a qualquer momento em Configurações. Seus dados pertencem a você \u2014 sem bloqueio.",
    "help.faq14Q": "O que acontece com meus dados se eu cancelar o Pro?",
    "help.faq14A": "Seus registros de treino estão seguros. Usuários gratuitos mantêm acesso total de leitura e capacidade de exportação. Apenas os recursos de análise avançada são pausados.",

    # === pro ===
    "pro.defaultFeature": "Este recurso",
    "pro.available": "Disponível no plano Pro",
    "pro.features": "Insights com IA para corrigir pontos fracos \u00b7 Nunca perca sua sequência novamente \u00b7 Seus dados, sempre exportáveis",
    "pro.bannerTitle": "\u26a1 Upgrade para Pro \u2014 $9,99/mês",
    "pro.bannerFeatures": "Encontre seus pontos fracos \u00b7 Acompanhe recuperação \u00b7 Proteja sua sequência",
    "pro.bannerCta": "Desbloquear Pro",
    "pro.socialProof": "Junte-se a mais de 500 atletas de BJJ treinando de forma mais inteligente",
    "pro.paymentIssueTitle": "Problema no pagamento \u2014 recursos Pro pausados",
    "pro.paymentIssueDesc": "Seu último pagamento falhou. Atualize suas informações de cobrança para continuar.",
    "pro.fixNow": "Corrigir agora",
    "pro.pastDueTitle": "Pagamento falhou",
    "pro.pastDueDesc": "Seu cartão pode ter expirado ou tem saldo insuficiente. Atualize suas informações de pagamento para manter o acesso Pro.",
    "pro.updateCard": "Atualizar cartão",
    "pro.canceledTitle": "Plano Pro cancelado",
    "pro.canceledDesc": "Os recursos premium estão desativados. Faça upgrade novamente para desbloquear todos os recursos.",
    "pro.rejoin": "Voltar",
    "pro.allFeaturesUnlocked": "Todos os recursos Pro desbloqueados",
    "pro.disclaimer": "Eu entendo que esta é uma assinatura digital e concordo com os Termos de Serviço. O BJJ App é um registro de treino, não substitui instrução qualificada.",
    "pro.disclaimerAria": "Reconhecimento do aviso de assinatura",

    # === csv ===
    "csv.exportFailed": "Falha na exportação",
    "csv.header.date": "Data",
    "csv.header.type": "Tipo",
    "csv.header.duration": "Duração (min)",
    "csv.header.result": "Resultado",
    "csv.header.opponent": "Oponente",
    "csv.header.finish": "Finalização",
    "csv.header.event": "Evento",
    "csv.header.notes": "Observações",
    "csv.header.techName": "Nome da Técnica",
    "csv.header.category": "Categoria",
    "csv.header.mastery": "Nível de Domínio",
    "csv.win": "Vitória",
    "csv.loss": "Derrota",
    "csv.draw": "Empate",
    "csv.button.training": "CSV",
    "csv.button.techniques": "CSV de Técnicas",
    "csv.button.pdf": "PDF",
    "csv.locked": "CSV (Pro)",
    "csv.pdfTitle": "Registros de Treino",
    "csv.pdfSubtitle": "BJJ App \u2014 Registro de Treinos",
    "csv.pdfGenerated": "Gerado em",
    "csv.pdfTotalSessions": "Total de Sessões",
    "csv.pdfTotalHours": "Total de Horas",
    "csv.pdfDateRange": "Período",
    "csv.pdfTo": "até",
    "csv.pdfHours": "hrs",
    "csv.pdfSessions": "sessões",
    "csv.pdfSummary": "Resumo",
    "csv.pdfNoData": "Nenhum registro de treino para exportar",
    "csv.pdfPrintHint": "Selecione \"Salvar como PDF\" para criar um arquivo PDF",

    # === report ===
    "report.title": "Relatório de Desempenho",
    "report.tabWeek": "Semana",
    "report.tabMonth": "Mês",
    "report.sessions": "Sessões",
    "report.totalTime": "Tempo Total",
    "report.avgTime": "Média/Sessão",
    "report.minUnit": "min",
    "report.maxStreak": "Melhor Sequência",
    "report.streakValue": "{n} dias",
    "report.typeDistribution": "Distribuição por Tipo de Treino",
    "report.weeklyTrend": "Tendência Semanal",
    "report.emptyState": "Registre pelo menos 2 semanas de treino para gerar seu relatório",
    "report.upgradeCta": "Desbloquear Relatório com Pro",
    "report.insightWeekUp": "Você treinou {n} vez(es) a mais que na semana passada!",
    "report.insightWeekDown": "Você treinou {n} vez(es) a menos que na semana passada. Continue firme!",
    "report.insightConsecutiveUp": "3 semanas de frequência crescente \u2014 ótimo ritmo!",
    "report.insightLowDrilling": "Sua proporção de drill está baixa esta semana. Considere adicionar sessões focadas em técnica.",
    "report.insightStreak": "Sua melhor sequência é de {n} dias consecutivos \u2014 consistência impressionante!",

    # === achievement ===
    "achievement.milestone.1.emoji": "\ud83c\udfaf",
    "achievement.milestone.1.text": "Primeiro treino registrado!",
    "achievement.milestone.1.subtext": "Sua jornada no BJJ começa!",
    "achievement.milestone.7.emoji": "\ud83d\udd25",
    "achievement.milestone.7.text": "7 sessões alcançadas!",
    "achievement.milestone.7.subtext": "Você está criando um hábito!",
    "achievement.milestone.10.emoji": "\ud83d\udcaa",
    "achievement.milestone.10.text": "10 sessões alcançadas!",
    "achievement.milestone.10.subtext": "O verdadeiro desafio começa!",
    "achievement.milestone.30.emoji": "\ud83c\udfc6",
    "achievement.milestone.30.text": "30 sessões alcançadas!",
    "achievement.milestone.30.subtext": "Um mês de dedicação!",
    "achievement.milestone.50.emoji": "\u2b50",
    "achievement.milestone.50.text": "50 sessões alcançadas!",
    "achievement.milestone.50.subtext": "O caminho para a Blue Belt está ao alcance!",
    "achievement.milestone.100.emoji": "\ud83d\udc4a",
    "achievement.milestone.100.text": "100 sessões!",
    "achievement.milestone.100.subtext": "Bem-vindo à classe guerreira do BJJ!",
    "achievement.milestone.200.emoji": "\ud83e\udd4b",
    "achievement.milestone.200.text": "200 sessões alcançadas!",
    "achievement.milestone.200.subtext": "O caminho da maestria está visível!",
    "achievement.milestone.365.emoji": "\ud83d\udc8e",
    "achievement.milestone.365.text": "365 sessões!",
    "achievement.milestone.365.subtext": "Um ano de dedicação! Verdadeira vida de BJJ!",
    "achievement.milestone.500.emoji": "\ud83c\udf96\ufe0f",
    "achievement.milestone.500.text": "500 sessões alcançadas!",
    "achievement.milestone.500.subtext": "Classe de conquista excepcional!",
    "achievement.milestone.1000.emoji": "\ud83d\udc51",
    "achievement.milestone.1000.text": "1.000 sessões alcançadas!",
    "achievement.milestone.1000.subtext": "Comprometimento de lenda do BJJ!",
    "achievement.shareButton": "Compartilhar no X",
    "achievement.shareText": "Acabei de atingir {n} sessões de treino no BJJ App! \ud83e\udd4b {text} #BJJ #ConsistencyWins #BrazilianJiuJitsu",

    # === beltPromo ===
    "beltPromo.congrats": "Parabéns! \ud83c\udf89",
    "beltPromo.advanced": "Você avançou de {from} para {to}. Continue rolando!",
    "beltPromo.shareOnX": "Compartilhar no X",
    "beltPromo.ariaDialog": "Celebração de promoção de faixa",
    "beltPromo.ariaShareX": "Compartilhar promoção de faixa no X (Twitter)",
    "beltPromo.oss": "OSS! \ud83d\udd25 Continuar",
    "beltPromo.keepRolling": "Tire um print \u2014 este modal não vai fechar sozinho.",
    "beltPromo.screenshotHint": "Toque em OSS quando estiver pronto para continuar.",

    # === ageGate ===
    "ageGate.body": "O BJJ App coleta dados de treino. Pela lei dos EUA (COPPA), precisamos verificar que você tem 13 anos de idade ou mais antes de continuar.",
    "ageGate.confirm": "\u2705 Eu tenho 13 anos ou mais",
    "ageGate.deny": "Eu tenho menos de 13 anos",
    "ageGate.footer": "Exigido pela lei federal dos EUA \u00b7 bjj-app.net",
    "ageGate.blockedTitle": "Restrição de Idade",
    "ageGate.blockedBody": "O BJJ App é projetado para usuários com 13 anos de idade ou mais. Não podemos permitir acesso para usuários com menos de 13 anos (conformidade COPPA).",
    "ageGate.blockedContact": "Se você acredita que isso é um erro, peça a um pai ou responsável para nos contatar em 307239t777@gmail.com",

    # === install ===
    "install.ios": "Adicione à Tela Inicial para usar como app!",
    "install.iosInstructions": "Safari \u2192 Compartilhar \u2192 \"Adicionar à Tela Inicial\"",
    "install.android": "Instale como app para usar offline!",
    "install.button": "Instalar",
    "install.installing": "Instalando...",
    "install.close": "Fechar banner",
    "install.error": "Instalação falhou. Por favor, tente novamente.",

    # === onboarding ===
    "onboarding.title": "Primeiros Passos",
    "onboarding.progress": "{done}/{total} completo",
    "onboarding.step.firstLog": "Registre sua primeira sessão de treino",
    "onboarding.step.setGoal": "Defina sua meta semanal de treino",
    "onboarding.step.addTechnique": "Adicione uma técnica à sua biblioteca",
    "onboarding.step.safetyAck": "Leia o aviso de segurança",
    "onboarding.safetyBanner": "\u26a0\ufe0f O BJJ envolve contato físico e risco de lesão. Sempre treine sob supervisão qualificada. Este app não substitui instrução profissional.",
    "onboarding.firstRollTitle": "Bem-vindo ao tatame! \ud83e\udd4b",
    "onboarding.firstRollDesc": "Seu primeiro rola está registrado. A jornada começou.",
    "onboarding.firstRollCta": "Vamos rolar \ud83e\udd1c",
    "onboarding.celebTitle": "Bem-vindo ao Tatame! \ud83e\udd4b",
    "onboarding.celebSubtitle": "Configuração completa \u2014 agora vá rolar!",

    # === freeze ===
    "freeze.title": "Streak Freeze",
    "freeze.protects": "Protege sua sequência em emergências",
    "freeze.used": "\u2744\ufe0f Streak Freeze usado! Sua sequência está salva.",
    "freeze.useFailed": "Falha ao usar. Por favor, tente novamente mais tarde.",
    "freeze.atRisk": "\ud83d\udd25 Sequência de {n} dias em risco! Streak Freeze disponível",
    "freeze.noYesterday": "Nenhum treino registrado ontem. Use um freeze para proteger sua sequência.",
    "freeze.remaining": "{n} usos restantes",
    "freeze.recentUsage": "Uso recente:",
    "freeze.using": "Usando...",
    "freeze.useBtn": "\u2744\ufe0f Usar Freeze ({n} restante)",
    "freeze.zeroRemaining": "Streak Freeze: 0 restante",
    "freeze.getUnlimited": "Obtenha freezes ilimitados com Pro",
    "freeze.goPro": "Assinar Pro \u2192",
    "freeze.paywallTitle": "Proteja sua sequência de {n} dias",
    "freeze.paywallSubtitle": "Streak Freezes são um recurso Pro. Faça upgrade para obter proteção ilimitada.",
    "freeze.paywallPoint1": "Streak Freezes Ilimitados",
    "freeze.paywallPoint2": "Heatmap de treino e análises",
    "freeze.paywallPoint3": "Acompanhamento corporal e de lesões",
    "freeze.paywallPoint4": "Análise de rolas (em breve)",
    "freeze.paywallCta": "Upgrade para Pro \u2014 $9,99/mês",
    "freeze.paywallDismiss": "Talvez depois",

    # === aiCoach ===
    "aiCoach.modeGeneral": "Semanal",
    "aiCoach.modeWeakness": "Pontos Fracos",
    "aiCoach.modeNextSession": "Próxima Sessão",
    "aiCoach.modeCompPrep": "Prep Competição",
    "aiCoach.section_challenge": "Desafio da Semana",
    "aiCoach.section_plan": "Plano de Ação",
    "aiCoach.section_sparring": "Plano de Sparring",
    "aiCoach.section_week_before": "Semana Antes da Competição",

    # === weightCut ===
    "weightCut.title": "Planejador de Corte de Peso",
    "weightCut.tolose": "A Perder",
    "weightCut.daysLeft": "Dias Restantes",
    "weightCut.daysUnit": "d",
    "weightCut.weeklyRate": "Taxa Semanal",
    "weightCut.weekUnit": "sem",
    "weightCut.aggressiveWarning": "Esta taxa de corte excede os limites seguros (>1kg/semana ou >10% do peso corporal). Considere estender seu prazo ou consultar um nutricionista esportivo.",
    "weightCut.phases": "Fases do Corte",
    "weightCut.phaseNormal": "Fase de Treino",
    "weightCut.phaseNormalAdvice": "Treine normalmente. Dieta limpa, leve déficit calórico. Foco na perda de peso sustentável.",
    "weightCut.phaseWaterLoad": "Carga de Água",
    "weightCut.phaseWaterLoadAdvice": "Aumente a ingestão de água para 6-8L/dia. Isso prepara seu corpo para eliminar água de forma eficiente depois.",
    "weightCut.phaseWaterCut": "Corte de Água",
    "weightCut.phaseWaterCutAdvice": "Reduza gradualmente a ingestão de água. Apenas treino leve. Monitore como você se sente de perto.",
    "weightCut.phaseWeighIn": "Dia da Pesagem",
    "weightCut.phaseWeighInAdvice": "Pese, depois reidrate imediatamente com eletrólitos e carboidratos leves.",
    "weightCut.milestones": "Metas Semanais",
    "weightCut.week": "Sem",
    "weightCut.alreadyAtTarget": "Você já está no peso alvo ou abaixo dele!",

    # === wiki ===
    "wiki.dailyTip": "Conhecimento BJJ de Hoje",
    "wiki.readMore": "Leia mais no Wiki",
    "wiki.close": "\u25b2 Fechar",
    "wiki.nextPreview": "Amanhã: {category} \u25bc",
    "wiki.nextHint": "Dica de amanhã",
    "wiki.peekAhead": "Prévia \u2192",

    # === skillmap ===
    "skillmap.tabRoots": "Pontos de Entrada",
    "skillmap.tabAll": "Todas as Técnicas",
    "skillmap.rootList": "Pontos de Entrada",
    "skillmap.emptyTitle": "Seu skill map está vazio",
    "skillmap.emptyBody": "Comece adicionando sua primeira técnica para construir seu mapa de BJJ.",
    "skillmap.emptyBodyPC": "Clique com o botão direito em qualquer lugar da tela para adicionar sua primeira técnica.",
    "skillmap.addFirstTechnique": "Adicionar primeira técnica",
    "skillmap.addTechniqueTitle": "Adicionar técnica",
    "skillmap.addSubTechnique": "Adicionar técnica conectada",
    "skillmap.namePlaceholder": "Nome da técnica",
    "skillmap.descPlaceholder": "Observações (opcional)",
    "skillmap.addBtn": "Adicionar",
    "skillmap.connectExisting": "Conectar a técnica existente",
    "skillmap.connectTitle": "Conectar técnicas",
    "skillmap.connectFrom": "De",
    "skillmap.connectTarget": "Selecionar alvo",
    "skillmap.selectTarget": "\u2014 selecionar \u2014",
    "skillmap.edgeLabelPlaceholder": "Rótulo da conexão (opcional)",
    "skillmap.connectBtn": "Conectar",
    "skillmap.leadsTo": "Leva a",
    "skillmap.noChildren": "Nenhuma conexão ainda.",
    "skillmap.noRoots": "Nenhuma técnica de ponto de entrada ainda.",
    "skillmap.openNode": "Abrir",
    "skillmap.deleteNode": "Remover",
    "skillmap.deleteEdge": "Remover conexão",
    "skillmap.proLockBtn": "Pro: Adicionar mais técnicas",
    "skillmap.proModalTitle": "Seu mapa está crescendo! \ud83d\udd25",
    "skillmap.proModalBody": "Você adicionou 10 técnicas. Faça upgrade para Pro para continuar construindo.",
    "skillmap.proModalTitlePC": "Você construiu um mapa impressionante! \ud83d\udd25",
    "skillmap.proModalBodyPC": "Faça upgrade para Pro para adicionar técnicas ilimitadas e desbloquear a sincronização com o Diário de Técnicas.",
    "skillmap.upgradeBtn": "Upgrade para Pro \u2014 $9,99/mês",
    "skillmap.upgradeAriaLabel": "Upgrade para o plano Pro",
    "skillmap.maybeLater": "Talvez depois",
    "skillmap.addNodeSuccess": "Técnica adicionada",
    "skillmap.addNodeError": "Falha ao adicionar técnica",
    "skillmap.addEdgeError": "Falha ao conectar técnicas",
    "skillmap.connectSuccess": "Conectado",
    "skillmap.deleteSuccess": "Excluído",
    "skillmap.cycleError": "Esta conexão criaria um ciclo \u2014 não permitido",
    "skillmap.pcHint": "Clique direito para adicionar \u00b7 Arraste o nó para mover \u00b7 Clique \u25cf para conectar",
    "skillmap.pcContextHint": "Clique direito ou tecla Tab para adicionar uma técnica",
    "skillmap.portHint": "Conectar a partir desta técnica",
    "skillmap.connectingHint": "Clique em outra técnica para conectar \u2192",
    "skillmap.resetView": "Resetar visualização",
    "skillmap.canvasShortcuts": "Atalhos de teclado da tela",
    "skillmap.magicOrganize": "Organizar Automaticamente",
    "skillmap.organizeSuccess": "Layout organizado \u2728",
    "skillmap.viewMode": "Visualizar",
    "skillmap.editMode": "Editar",
    "skillmap.drawerAddChild": "Adicionar Técnica Filha",
    "skillmap.drawerAddChildHint": "Digite um nome para a técnica filha",
    "skillmap.drawerConnect": "Conectar a Existente",
    "skillmap.drawerRemove": "Remover Nó",
    "skillmap.connectMobileHint": "Toque em uma técnica para conectar \u2192",
    "skillmap.deleteConfirmMsg": "Remover esta técnica e suas conexões?",
    "skillmap.addNodeMobile": "Adicionar Técnica",
    "skillmap.fullScreen": "Tela Cheia",
    "skillmap.exitFullScreen": "Sair da Tela Cheia",
    "skillmap.overLimitBanner": "Você excedeu o limite gratuito. Faça upgrade para Pro para continuar editando suas {count} técnicas.",
    "skillmap.overLimitUpgrade": "Upgrade para Pro",

    # === landing ===
    "landing.navLogin": "Entrar",
    "landing.navGetStarted": "Começar",
    "landing.heroBadge": "Grátis para começar",
    "landing.heroTitle1": "Prove seu crescimento no BJJ",
    "landing.heroTitle2": "com dados reais.",
    "landing.heroDesc": "Acompanhe sessões, técnicas e sequências em um só lugar.\nCada dia que você registra é um passo mais perto da próxima faixa.",
    "landing.heroCta": "Começar a Registrar Grátis",
    "landing.heroSeeApp": "Ver o app",
    "landing.heroSubtext": "Entre com GitHub ou Google. Sem cartão de crédito.",
    "landing.heroGuest": "Experimentar sem cadastro \u2192",
    "landing.engTitle1": "Pare de esquecer o que aprendeu.",
    "landing.engTitle2": "Registre cada técnica.",
    "landing.engDesc": "Você treina um movimento. Esquece na semana seguinte.\nO BJJ App resolve isso \u2014 registre suas sessões, salve técnicas com níveis de domínio e mantenha sua sequência de treino viva.",
    "landing.engPillSession": "Registro de sessão (Gi / NoGi / Drill)",
    "landing.engPillTechnique": "Caderno de técnicas",
    "landing.engPillStreak": "Sequência de treino",
    "landing.engPillGoals": "Metas semanais e mensais",
    "landing.engPillHeatmap": "Heatmap de calendário",
    "landing.engPillComp": "Registro de competições V/D",
    "landing.engPillSkillMap": "Skill map visual",
    "landing.engCta": "Começar a Registrar Grátis",
    "landing.engGuest": "Experimentar sem cadastro",
    "landing.engSubtext": "Sem cartão de crédito. Entre com GitHub ou Google. Leva 30 segundos.",
    "landing.proofBadge": "\u2705 Confiado por lutadores no mundo todo",
    "landing.proofTitle": "Dados reais de treino",
    "landing.proofSessions": "50.000+",
    "landing.proofSessionsLabel": "Sessões registradas",
    "landing.proofTechniques": "1.200+",
    "landing.proofTechniquesLabel": "Técnicas salvas",
    "landing.proofStreak": "30+",
    "landing.proofStreakLabel": "Maior sequência (dias)",
    "landing.proofFree": "Grátis",
    "landing.proofFreeLabel": "Todos os recursos principais",
    "landing.stepsTitle": "3 passos para progresso visível",
    "landing.step1Title": "Registre",
    "landing.step1Desc": "Registre cada sessão. Data, duração, tipo e notas em segundos. Funciona perfeitamente no celular.",
    "landing.step2Title": "Acompanhe",
    "landing.step2Desc": "Seu dashboard atualiza em tempo real. Sequência, progresso de metas e contagem de técnicas em um olhar.",
    "landing.step3Title": "Melhore",
    "landing.step3Desc": "Identifique suas áreas fracas e corrija-as. Dados provam seu progresso e mantêm a motivação alta.",
    "landing.previewTitle": "Veja como funciona",
    "landing.previewSubtitle": "Pronto para usar logo após o cadastro. Recursos principais grátis para sempre.",
    "landing.featureLogTitle": "Registre cada sessão",
    "landing.featureLogDesc": "Acompanhe Gi, NoGi, drill, competição e open mat. Revise seu calendário a qualquer momento.",
    "landing.featureGoalsTitle": "Defina metas semanais e mensais",
    "landing.featureGoalsDesc": "Acompanhe seu objetivo com uma barra de progresso. Fica verde quando você atinge.",
    "landing.featureWeakTitle": "Identifique seus pontos fracos",
    "landing.featureWeakDesc": "Organize técnicas por posição. Avaliações por estrelas mostram onde você precisa trabalhar.",
    "landing.featureStreakTitle": "Construa uma sequência",
    "landing.featureStreakDesc": "Conta automaticamente seus dias consecutivos de treino. Difícil de deixar quebrar.",
    "landing.featureCalendarTitle": "Visualização em calendário",
    "landing.featureCalendarDesc": "Veja seus dias de treino em um calendário mensal com pontos coloridos por tipo.",
    "landing.featureSkillMapTitle": "Skill Map Visual",
    "landing.featureSkillMapDesc": "Construa um mapa mental das suas técnicas. Veja as conexões entre posições e submissions.",
    "landing.featureStartCta": "Comece a registrar seus dados",
    "landing.coreLogTitle": "Registro de Treino",
    "landing.coreLogDesc": "Registre data, duração, tipo e notas. Totaliza automaticamente suas sessões mensais e tempo de treino.",
    "landing.coreTechTitle": "Diário de Técnicas",
    "landing.coreTechDesc": "Organize técnicas por posição. Acompanhe níveis de domínio para identificar e corrigir pontos fracos.",
    "landing.coreStreakTitle": "Sequência de Dias",
    "landing.coreStreakDesc": "Conta automaticamente seus dias consecutivos de treino. A sequência faz você voltar sempre.",
    "landing.coreSkillMapTitle": "Skill Map Visual",
    "landing.coreSkillMapDesc": "Mapeie suas técnicas. Visualize as conexões entre posições e submissions.",
    "landing.wikiTitle": "Aprofunde Seu Conhecimento em BJJ",
    "landing.wikiSubtitle": "4.000+ páginas de enciclopédia gratuita de técnicas de BJJ \u2014 do iniciante ao avançado",
    "landing.wikiGuardTitle": "Sistemas de Guard",
    "landing.wikiGuardDesc": "Closed, Half, Spider, DLR",
    "landing.wikiLegTitle": "Leg Locks",
    "landing.wikiLegDesc": "Heel hooks, Ashi garami, Toe holds",
    "landing.wikiCompTitle": "Mentalidade de Competição",
    "landing.wikiCompDesc": "Preparação para luta, nervosismo, estratégia",
    "landing.wikiNutritionTitle": "Nutrição e Recuperação",
    "landing.wikiNutritionDesc": "Dieta para atletas de BJJ, prevenção de lesões",
    "landing.wikiExplore": "Explorar o BJJ Wiki",
    "landing.faqTitle": "Perguntas Frequentes",
    "landing.faq1Q": "É realmente grátis?",
    "landing.faq1A": "Sim, todos os recursos principais são completamente gratuitos. Registro de treino, diário de técnicas, acompanhamento de metas, calendário e gráficos são todos gratuitos. O plano Pro ($9,99/mês) desbloqueia Skill Map ilimitado, gráficos de 12 meses e streak freeze.",
    "landing.faq2Q": "É bom para iniciantes?",
    "landing.faq2A": "Com certeza! White belts e blue belts são os usuários perfeitos. Feito para resolver dois problemas comuns: não lembrar nomes de técnicas e manter a consistência. Registrar desde o primeiro dia torna o caminho para sua próxima faixa visível.",
    "landing.faq3Q": "Como é diferente de um caderno?",
    "landing.faq3A": "Três diferenças principais: (1) Contagem automática de sequência \u2014 nunca perca o ritmo, (2) Gráficos visuais \u2014 veja seu crescimento em números, (3) Integração com BJJ Wiki \u2014 consulte instantaneamente qualquer técnica de 4.000+ páginas. Dados provam seu progresso.",
    "landing.faq4Q": "Funciona no celular?",
    "landing.faq4A": "Sim! Totalmente responsivo e funciona perfeitamente no navegador do seu smartphone. Adicione à tela inicial para usar como app nativo.",
    "landing.faq5Q": "Meus dados estão seguros?",
    "landing.faq5A": "Os dados são armazenados com segurança no Supabase (PostgreSQL de nível empresarial). Row Level Security significa que ninguém pode acessar seus dados. Exporte tudo como CSV a qualquer momento \u2014 sem bloqueio.",
    "landing.finalCtaTitle": "Comece a Treinar de Forma Mais Inteligente Hoje",
    "landing.finalCtaSubtitle": "Sem cartão de crédito. Cadastre-se com GitHub ou Google em segundos.",
    "landing.finalCtaButton": "Começar a Registrar Grátis",
    "landing.footerCopyright": "\u00a9 2026 BJJ App. Todos os direitos reservados.",
    "landing.footerTerms": "Termos de Serviço",
    "landing.footerPrivacy": "Política de Privacidade",
    "landing.footerTokushoho": "\u7279\u5b9a\u5546\u53d6\u5f15\u6cd5\u306b\u57fa\u3065\u304f\u8868\u8a18",

    # === gymLanding ===
    "gymLanding.navIndividuals": "Para Indivíduos",
    "gymLanding.navSignIn": "Entrar",
    "gymLanding.navDashboard": "Abrir Dashboard \u2192",
    "gymLanding.heroBadge": "Para Donos de Academia e Coaches",
    "gymLanding.heroTitle1": "Mantenha Seus Alunos",
    "gymLanding.heroTitle2": "Engajados Entre as Aulas",
    "gymLanding.heroDesc": "Dashboard de academia que acompanha quais alunos estão treinando, envia atualizações de currículo e identifica alunos em risco de evasão antes que saiam.",
    "gymLanding.heroCta": "Abrir Dashboard \u2014 Grátis \u2192",
    "gymLanding.heroWaitlist": "Ou entrar na lista de espera \u2192",
    "gymLanding.featuresTitle": "O Que Você Recebe",
    "gymLanding.feature1Title": "Dashboard de Risco de Evasão",
    "gymLanding.feature1Desc": "Sinaliza automaticamente alunos que não registraram treino em 2+ semanas. Veja seus alunos em risco antes que desapareçam.",
    "gymLanding.feature1Point1": "Sistema de alerta em tempo real",
    "gymLanding.feature1Point2": "Contate alunos antes que seja tarde",
    "gymLanding.feature1Point3": "Reduza a evasão em 20-30%",
    "gymLanding.feature2Title": "Envio Semanal de Currículo",
    "gymLanding.feature2Desc": "Vincule a técnica da semana do BJJ Wiki. Todos os seus alunos veem no app. Estenda o aprendizado da aula para a preparação em casa.",
    "gymLanding.feature2Point1": "Envie em 30 segundos",
    "gymLanding.feature2Point2": "4.000+ páginas gratuitas do BJJ Wiki disponíveis",
    "gymLanding.feature2Point3": "Aumente a retenção de alunos",
    "gymLanding.feature3Title": "Sistema de Convite por QR",
    "gymLanding.feature3Desc": "Gere um QR code único para sua academia. Alunos escaneiam e entram automaticamente no seu grupo. Onboarding sem atrito.",
    "gymLanding.feature3Point1": "Imprima em panfletos e cartazes",
    "gymLanding.feature3Point2": "Compartilhe via email/WhatsApp",
    "gymLanding.feature3Point3": "Integração instantânea à turma",
    "gymLanding.howTitle": "Como Funciona",
    "gymLanding.step1Title": "Alunos Baixam",
    "gymLanding.step1Desc": "Seus alunos acessam o BJJ App pela web (sem app store). Podem usar sozinhos ou entrar no grupo da sua academia.",
    "gymLanding.step2Title": "Escaneiam Seu QR",
    "gymLanding.step2Desc": "Eles escaneiam o QR code único da sua academia. Conectados instantaneamente aos dados do seu gym. Sem formulários, sem atrito, pronto.",
    "gymLanding.step3Title": "Você Acompanha e Engaja",
    "gymLanding.step3Desc": "Veja quem está ativo, quem está sumindo, e envie atualizações de currículo. Alunos têm uma experiência de prática mais forte.",
    "gymLanding.pricingTitle": "Preços Simples",
    "gymLanding.pricingPopular": "Popular",
    "gymLanding.pricingStarter": "Starter",
    "gymLanding.pricingMonth": "mês",
    "gymLanding.pricingStarterLimit": "Até 50 alunos",
    "gymLanding.pricingStarterF1": "Dashboard de risco de evasão",
    "gymLanding.pricingStarterF2": "Envio semanal de currículo",
    "gymLanding.pricingStarterF3": "Sistema de convite por QR",
    "gymLanding.pricingStarterF4": "Suporte por email",
    "gymLanding.pricingPro": "Pro",
    "gymLanding.pricingProLimit": "Alunos ilimitados",
    "gymLanding.pricingProF1": "Tudo do Starter",
    "gymLanding.pricingProF2": "Grupos de alunos ilimitados",
    "gymLanding.pricingProF3": "Análises avançadas",
    "gymLanding.pricingProF4": "Suporte prioritário",
    "gymLanding.pricingCta": "Solicitar Acesso",
    "gymLanding.pricingNote": "\ud83d\udce9 Envie-nos um email para planos personalizados. Teste grátis de 14 dias incluído.",
    "gymLanding.waitlistTitle": "Obtenha Acesso Antecipado",
    "gymLanding.waitlistDesc": "Os recursos para academias estão em beta privado. Entre na lista de espera e entraremos em contato quando sua vaga estiver pronta.",
    "gymLanding.faqTitle": "Dúvidas?",
    "gymLanding.faq1Q": "Os alunos precisam pagar?",
    "gymLanding.faq1A": "Não. Alunos usam o BJJ App gratuitamente. Você paga pelos recursos de gestão da academia. Alunos se beneficiam do currículo e do próprio acompanhamento \u2014 sem custo para eles.",
    "gymLanding.faq2Q": "Tem taxa de configuração?",
    "gymLanding.faq2A": "Sem taxa de configuração. Sem contratos. Você pode cancelar a qualquer momento. Pegue seu QR code e comece a usar imediatamente após o cadastro.",
    "gymLanding.faq3Q": "Posso usar com Stripe/PayPal para mensalidades?",
    "gymLanding.faq3A": "No momento, o app foca em engajamento e retenção. Estamos planejando integração de pagamento para uma atualização futura. Por enquanto, use seu sistema de pagamento existente.",
    "gymLanding.faq4Q": "Preciso de habilidades técnicas?",
    "gymLanding.faq4A": "Não. Tudo é feito no navegador. Gere seu QR code, compartilhe com alunos, envie currículo via link. É isso.",
    "gymLanding.faq5Q": "E se os alunos pararem de usar o app?",
    "gymLanding.faq5A": "O dashboard mostra quem está ativo e quem não está. Você perceberá o desengajamento antes que os alunos saiam da sua academia. Esse é o objetivo.",
    "gymLanding.finalCtaTitle": "Pronto para engajar seu time?",
    "gymLanding.finalCtaDesc": "Teste grátis de 14 dias. Sem cartão de crédito. Cancele a qualquer momento.",
    "gymLanding.finalCtaButton": "Solicitar Demo \u2192",
    "gymLanding.footerCopyright": "\u00a9 2026 BJJ App. Feito por lutadores, para lutadores.",
    "gymLanding.footerTerms": "Termos",
    "gymLanding.footerPrivacy": "Privacidade",
    "gymLanding.footerTokushoho": "\u7279\u5b9a\u5546\u53d6\u5f15\u6cd5\u306b\u57fa\u3065\u304f\u8868\u8a18",

    # === gym ===
    "gym.atChurnRisk": "{n} alunos em risco de evasão",
    "gym.upgradeToSee": "Faça upgrade para Gym Pro para ver quem \u2014 e entre em contato antes que desistam.",
    "gym.activeSection": "\ud83d\udfe2 Membros Ativos ({n})",
    "gym.slowingSection": "\ud83d\udfe1 Diminuindo ritmo ({n})",
    "gym.highRiskSection": "\ud83d\udd34 Alto risco de evasão ({n})",
    "gym.lastSeen": "Visto por último: {text}",
    "gym.sessionsPerMonth": "{n} sessões/30d",
    "gym.detailsHidden": "\ud83d\udd12 Detalhes ocultos \u2014",
    "gym.upgradeToSeeLink": "faça upgrade para ver",
    "gym.today": "Hoje",
    "gym.yesterday": "Ontem",
    "gym.daysAgo": "{n} dias atrás",
    "gym.never": "Nunca",
    "gym.createError": "Falha ao criar academia. Por favor, tente novamente.",
    "gym.waitlistEmailLabel": "Seu email *",
    "gym.waitlistGymLabel": "Nome da Academia",
    "gym.waitlistEmailPlaceholder": "coach@suaacademia.com",
    "gym.waitlistGymPlaceholder": "Triangle BJJ Academy",
    "gym.waitlistJoining": "Entrando...",
    "gym.waitlistJoin": "Entrar na Lista de Espera \u2192",
    "gym.waitlistNoSpam": "Sem spam. Enviaremos um email quando os recursos para academias forem lançados.",
    "gym.waitlistSuccess": "Você está na lista!",
    "gym.waitlistSuccessDesc": "Entraremos em contato quando os recursos para academias estiverem prontos. Enquanto isso, incentive seus alunos a baixar o BJJ App \u2014 quanto mais entrarem, mais rápido entramos em contato.",
    "gym.waitlistError": "Algo deu errado. Por favor, tente novamente.",
    "gym.waitlistNetworkError": "Erro de rede. Por favor, verifique sua conexão.",
    "gym.currentGym": "\ud83c\udfeb Academia Atual",
    "gym.unknownGym": "Academia desconhecida",
    "gym.leaveGym": "Sair da academia",
    "gym.leaving": "Saindo...",
    "gym.leaveConfirmTitle": "Sair de {name}?",
    "gym.leaveConfirmDesc": "O dono da academia não verá mais seus dados de treino. Você pode voltar com um novo QR code.",
    "gym.membersLabel": "membros",
    "gym.totalSessions30d": "Total de sessões (30d)",
    "gym.avgSessions30d": "Média de sessões/membro",
    "gym.memberKicked": "Membro removido da academia.",
    "gym.kickFailed": "Falha ao remover membro. Por favor, tente novamente.",
    "gym.kickedBannerTitle": "Você foi removido da sua academia",
    "gym.kickedBannerDesc": "Você não é mais membro da sua academia anterior. Você pode entrar em uma nova academia com um link de convite.",
    "gym.kickedBannerDismiss": "Entendi",
    "gym.rankingTitle": "Atividade de Treino",
    "gym.myRank": "Sua posição: #{n}",
    "gym.rankingMe": "Você",
    "gym.rankingAnon": "Colega de treino",
    "gym.rankingFootnote": "Apenas membros que optaram \u00b7 Nomes ocultos por privacidade",
    "gym.rankingSessions": "Sessões",
    "gym.rankingStreak": "Sequência",
    "gym.rankingStreakRestHint": "Dias de descanso previnem lesões \u2014 sequências são para diversão, não pressão.",
    "gym.noMembersHint": "Membros aparecerão aqui quando optarem por compartilhar seus dados de treino",
    "gym.rankingOptIn": "Participar do compartilhamento de atividade",
    "gym.rankingOptOut": "Sair do compartilhamento de atividade",
    "gym.rankingOptInHint": "Compartilhe suas estatísticas de treino com membros da academia",
    "gym.rankingOptOutHint": "Remover-se da visualização de atividade",
    "gym.rankingToggling": "Atualizando...",
    "gym.curriculumCardTitle": "\ud83d\udcda Currículo de Hoje da sua academia",
    "gym.curriculumCardCta": "Ver artigo \u2192",
    "gym.regenerateConfirm": "Regenerar código de convite? Todos os QR codes e links existentes se tornarão inválidos. Membros atuais não são afetados.",
    "gym.regenerating": "Regenerando...",
    "gym.regenerateBtn": "\ud83d\udd04 Regenerar QR code (invalida links antigos)",
    "gym.removeMemberConfirm": "Tem certeza de que deseja remover {name} da sua academia?",
    "gym.removeMemberNote": "Eles serão notificados e podem voltar usando o QR code.",
    "gym.removeMemberBtn": "Remover membro",
    "gym.removeMemberTitle": "Remover da academia",
    "gym.sentToday": "Enviado hoje",
    "gym.sentYesterday": "Enviado ontem",
    "gym.sentDaysAgo": "Enviado {n} dias atrás",
    "gym.curriculumPracticedBtn": "\u2610 Praticado",
    "gym.curriculumPracticedDone": "\u2611 Praticado!",
    "gym.ariaCopyInvite": "Copiar link de convite",
    "gym.ariaRegenerate": "Regenerar código de convite (invalida QR codes antigos)",
    "gym.ariaUpgradePro": "Upgrade para Gym Pro",
    "gym.invalidInviteTitle": "Link de convite inválido",
    "gym.invalidInviteDesc": "Este link de convite da academia não é mais válido ou expirou.",
    "gym.goToDashboard": "Ir para o dashboard",
    "gym.defaultOwnerName": "Dono da Academia",
    "gym.atChurnRisk1": "1 aluno em risco de evasão",
    "gym.nudgeCopy": "Copiar lembrete",
    "gym.nudgeCopied": "Copiado!",
    "gym.nudgeTemplate": "Ei! Sentimos sua falta no tatame. Venha treinar com a gente logo! \ud83e\udd4b",
    "gym.nudgeAriaLabel": "Copiar mensagem de lembrete para {name}",
    "gym.shareWhatsApp": "Compartilhar via WhatsApp",
    "gym.shareOther": "Compartilhar link",
    "gym.csvInstructions": "Cole os emails dos alunos abaixo \u2014 um por linha, ou CSV com uma coluna 'email'. Opcionalmente adicione uma coluna 'name'.",
    "gym.csvPlaceholder": "alice@example.com\nbob@example.com\n\nOU cole CSV:\nname,email\nAlice Smith,alice@example.com\nBob Jones,bob@example.com",
    "gym.csvResult": "{n} alunos encontrados",
    "gym.csvReset": "Recomeçar",
    "gym.csvNote": "Todos os alunos usam o mesmo link de convite \u2014 o código de convite garante que eles entrem na sua academia.",

    # === gymJoin ===
    "gymJoin.title": "Entrar em {name}",
    "gymJoin.managedBy": "Gerenciado por: {owner}",
    "gymJoin.ownerCanSee": "O que o dono da academia pode ver:",
    "gymJoin.canSeeFrequency": "Sua frequência de treino (contagem de sessões + datas apenas)",
    "gymJoin.canSeeBelt": "Sua graduação de faixa",
    "gymJoin.cannotSeeNotes": "Suas notas de treino (sempre privadas)",
    "gymJoin.cannotSeeComp": "Seus detalhes de competição (sempre privados)",
    "gymJoin.joining": "Entrando...",
    "gymJoin.joinAndShare": "Sim, entrar e compartilhar meus dados de treino",
    "gymJoin.joinNoShare": "Entrar sem compartilhar (usar o app apenas para mim)",
    "gymJoin.privacyNote": "Você pode alterar sua preferência de compartilhamento a qualquer momento em Configurações do Perfil. Sair da academia remove permanentemente seus dados do dashboard do dono.",
    "gymJoin.error": "Falha ao entrar na academia. Por favor, tente novamente.",
    "gymJoin.transferTitle": "Transferir de Academia?",
    "gymJoin.transferDesc": "Você está atualmente em outra academia. Entrar em {name} vai removê-lo da sua academia atual, e o dono anterior não verá mais seus dados.",
    "gymJoin.transferYes": "Sim, transferir para {name}",
    "gymJoin.ariaAgeConfirm": "Confirmação de idade: Eu tenho 13 anos de idade ou mais",
    "gymJoin.ariaJoinShare": "Entrar na academia e compartilhar dados de treino",
    "gymJoin.ariaJoinNoShare": "Entrar na academia sem compartilhar dados",
}

# Verify we have all filtered keys covered
missing = set(filtered_keys.keys()) - set(translations.keys())
if missing:
    print(f"WARNING: {len(missing)} keys not translated:")
    for k in sorted(missing):
        print(f"  - {k}")
else:
    print(f"All {len(translations)} keys translated successfully.")

# Write output
with open("/tmp/pt_batch3.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print(f"Output written to /tmp/pt_batch3.json")
