#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Batch 3: Portuguese translations for BJJ App.
Sections: landing, gymLanding, gym, gymJoin, login, help, pro, pricing, proModal,
csv, report, achievement, extendedBadges, beltPromo, ageGate, install, onboarding,
guest, freeze, aiCoach, weightCut, wiki, skillmap.
"""

import json

TARGET_SECTIONS = {
    "landing", "gymLanding", "gym", "gymJoin", "login", "help", "pro",
    "pricing", "proModal", "csv", "report", "achievement", "extendedBadges",
    "beltPromo", "ageGate", "install", "onboarding", "guest", "freeze",
    "aiCoach", "weightCut", "wiki", "skillmap",
}

# Read the missing keys
with open("/tmp/pt_missing_keys.json", "r", encoding="utf-8") as f:
    all_keys = json.load(f)

# Filter for target sections
filtered_keys = {
    k: v for k, v in all_keys.items()
    if k.split(".")[0] in TARGET_SECTIONS
}

# Hardcoded Portuguese translations
# NOTE: For emoji-only keys (achievement.milestone.*.emoji), we copy from source.
# All other translations use proper UTF-8 strings.

translations = {}

# --- Keys whose value is emoji-only: copy verbatim from source ---
COPY_FROM_SOURCE = {
    "achievement.milestone.1.emoji",
    "achievement.milestone.7.emoji",
    "achievement.milestone.10.emoji",
    "achievement.milestone.30.emoji",
    "achievement.milestone.50.emoji",
    "achievement.milestone.100.emoji",
    "achievement.milestone.200.emoji",
    "achievement.milestone.365.emoji",
    "achievement.milestone.500.emoji",
    "achievement.milestone.1000.emoji",
}

for k in COPY_FROM_SOURCE:
    if k in filtered_keys:
        translations[k] = filtered_keys[k]

# --- All other translations ---
_t = {
    # === guest ===
    "guest.banner": "Modo Visitante",
    "guest.signupLink": "Entrar no Tatame",
    "guest.saveToCloud": " para salvar seus dados na nuvem",
    "guest.welcome": "Bem-vindo! " + "\U0001F44B",
    "guest.noLogin": "Experimentar sem cadastro",
    "guest.sessions": "Sess\u00f5es Registradas",
    "guest.totalMins": "Minutos Totais",
    "guest.ctaRecorded": "\U0001F4DD {n} sess\u00f5es registradas!",
    "guest.ctaTitle": "Salvar seu progresso na nuvem?",
    "guest.ctaDesc": "Cadastre-se gratuitamente para sincronizar entre dispositivos, ver o calend\u00e1rio e acompanhar metas",
    "guest.ctaButton": "Entrar no Tatame \u2192",
    "guest.ctaNote": "\u203b Seus dados de visitante ser\u00e3o migrados automaticamente ap\u00f3s o cadastro",
    "guest.migrated": "\U0001F389 {n} sess\u00e3o(\u00f5es) de visitante migrada(s) para sua conta!",

    # === login ===
    "login.github": "GitHub (para desenvolvedores)",
    "login.ageConfirm": "13 anos de idade ou mais",
    "login.ageConfirmNote": "(exigido por lei dos EUA)",
    "login.parentalConsent": "Idades entre 13\u201317 requerem consentimento dos pais ou respons\u00e1vel.",
    "login.disclaimerConfirm": "Eu entendo que o BJJ envolve risco f\u00edsico e concordo em treinar de forma respons\u00e1vel. N\u00e3o responsabilizarei o BJJ App por quaisquer les\u00f5es.",
    "login.checkboxesRequired": "\u2757 Por favor, marque ambas as caixas acima para continuar",
    "login.iabWarning": "Abrir no Safari ou Chrome",
    "login.iabDesc": "O login n\u00e3o \u00e9 suportado nos navegadores integrados do Instagram / LINE / X. Por favor, copie a URL e abra no seu navegador padr\u00e3o.",
    "login.iabCopy": "Copiar URL",
    "login.iabCopied": "\u2705 Copiado!",
    "login.ageConfirmPre": "Eu tenho",
    "login.disclaimerPre": "Eu entendo que",
    "login.disclaimerRisk": "o BJJ envolve risco f\u00edsico",
    "login.disclaimerPost": "e concordo em treinar de forma respons\u00e1vel. N\u00e3o responsabilizarei o BJJ App por quaisquer les\u00f5es.",
    "login.orEmail": "ou continue com email",
    "login.iabPaste": "Cole na barra de endere\u00e7o do Safari ou Chrome para continuar",
    "login.errorCallback": "Erro no login. Por favor, tente novamente.",
    "login.errorDenied": "Acesso negado.",
    "login.errorGeneric": "Ocorreu um erro. Por favor, tente novamente.",
    "login.ariaAgeConfirm": "Confirma\u00e7\u00e3o de idade: Eu tenho 13 anos de idade ou mais",
    "login.ariaDisclaimerConfirm": "Aviso de treino: Eu entendo que o BJJ envolve risco f\u00edsico",
    "login.ariaSignInGoogle": "Entrar com Google",
    "login.ariaEmailAddress": "Endere\u00e7o de email",
    "login.ariaSendMagicLink": "Enviar link m\u00e1gico de login",
    "login.ariaSignInGitHub": "Entrar com GitHub",

    # === help ===
    "help.title": "Ajuda e FAQ",
    "help.subtitle": "Perguntas frequentes sobre o BJJ App",
    "help.back": "Voltar ao Dashboard",
    "help.faq1Q": "Como registro uma sess\u00e3o de treino?",
    "help.faq1A": "Toque no bot\u00e3o + no seu dashboard, selecione o tipo de treino (Gi, No-Gi, Drill, etc.), dura\u00e7\u00e3o e observa\u00e7\u00f5es. Sua sess\u00e3o \u00e9 salva instantaneamente.",
    "help.faq2Q": "Como funciona o contador de sequ\u00eancia?",
    "help.faq2A": "Sua sequ\u00eancia conta dias consecutivos com pelo menos uma sess\u00e3o registrada. Treinos ap\u00f3s meia-noite contam como o mesmo dia at\u00e9 4h (data l\u00f3gica de treino). Use o Streak Freeze (Pro) para proteger sua sequ\u00eancia em dias de descanso.",
    "help.faq3Q": "Posso mudar minha faixa?",
    "help.faq3A": "Sim! V\u00e1 em Perfil e toque na sua faixa para alter\u00e1-la. Se voc\u00ea for promovido, ver\u00e1 uma anima\u00e7\u00e3o de celebra\u00e7\u00e3o.",
    "help.faq4Q": "Como altero meu email ou nome de exibi\u00e7\u00e3o?",
    "help.faq4A": "V\u00e1 em Perfil > Conta. Voc\u00ea pode alterar seu email (um link de confirma\u00e7\u00e3o ser\u00e1 enviado) ou atualizar seu nome de exibi\u00e7\u00e3o.",
    "help.faq5Q": "Como excluir minha conta?",
    "help.faq5A": "V\u00e1 em Perfil > Conta > Excluir Conta. Digite DELETE para confirmar. Todos os seus dados ser\u00e3o removidos permanentemente (conforme GDPR/CCPA).",
    "help.faq6Q": "O que \u00e9 o Dashboard do Gym?",
    "help.faq6A": "O Dashboard do Gym permite que donos de academia acompanhem a atividade dos alunos, enviem curr\u00edculo e reduzam a evas\u00e3o. Alunos entram via QR code e podem controlar quais dados compartilham.",
    "help.faq7Q": "O que inclui o Pro?",
    "help.faq7A": "O Pro desbloqueia an\u00e1lises avan\u00e7adas (gr\u00e1ficos de treino de 12 meses, gerenciamento corporal, streak freeze), skill maps de t\u00e9cnicas e suporte priorit\u00e1rio. $9,99/m\u00eas.",
    "help.faq8Q": "Como exporto meus dados?",
    "help.faq8A": "V\u00e1 em Perfil > Conta > Baixar meus dados (CSV). Todos os seus registros de treino ser\u00e3o exportados como arquivo CSV que voc\u00ea pode abrir em qualquer planilha.",
    "help.contactTitle": "Ainda precisa de ajuda?",
    "help.contactBtn": "Enviar Email ao Suporte",
    "help.faq9Q": "Minha sess\u00e3o de treino n\u00e3o salvou?",
    "help.faq9A": "Verifique sua conex\u00e3o de rede. As sess\u00f5es s\u00e3o salvas no servidor quando online. Se o problema persistir, tente atualizar a p\u00e1gina.",
    "help.faq10Q": "Como cancelo minha assinatura Pro?",
    "help.faq10A": "V\u00e1 em Perfil > Conta > Gerenciar Assinatura. Voc\u00ea pode cancelar com um clique. Os recursos Pro permanecem dispon\u00edveis at\u00e9 o final do per\u00edodo de cobran\u00e7a.",
    "help.faq11Q": "Como exporto um relat\u00f3rio em PDF?",
    "help.faq11A": "Na p\u00e1gina de Registros, clique no bot\u00e3o Exportar e selecione PDF. Um relat\u00f3rio com seu resumo de treino e estat\u00edsticas ser\u00e1 gerado.",
    "help.faq12Q": "N\u00e3o estou recebendo notifica\u00e7\u00f5es",
    "help.faq12A": "Verifique as configura\u00e7\u00f5es de notifica\u00e7\u00e3o do seu navegador. No iOS Safari, voc\u00ea precisa adicionar o app \u00e0 Tela Inicial antes de ativar notifica\u00e7\u00f5es.",
    "help.troubleshootingTitle": "Solu\u00e7\u00e3o de Problemas",
    "help.troubleshootingSubtitle": "Problemas comuns e solu\u00e7\u00f5es",
    "help.faq13Q": "Posso exportar meus dados de treino?",
    "help.faq13A": "Sim! Voc\u00ea pode exportar todo o seu hist\u00f3rico de treino como CSV ou PDF a qualquer momento em Configura\u00e7\u00f5es. Seus dados pertencem a voc\u00ea \u2014 sem bloqueio.",
    "help.faq14Q": "O que acontece com meus dados se eu cancelar o Pro?",
    "help.faq14A": "Seus registros de treino est\u00e3o seguros. Usu\u00e1rios gratuitos mant\u00eam acesso total de leitura e capacidade de exporta\u00e7\u00e3o. Apenas os recursos de an\u00e1lise avan\u00e7ada s\u00e3o pausados.",

    # === pro ===
    "pro.defaultFeature": "Este recurso",
    "pro.available": "Dispon\u00edvel no plano Pro",
    "pro.features": "Insights com IA para corrigir pontos fracos \u00b7 Nunca perca sua sequ\u00eancia novamente \u00b7 Seus dados, sempre export\u00e1veis",
    "pro.bannerTitle": "\u26a1 Upgrade para Pro \u2014 $9,99/m\u00eas",
    "pro.bannerFeatures": "Encontre seus pontos fracos \u00b7 Acompanhe recupera\u00e7\u00e3o \u00b7 Proteja sua sequ\u00eancia",
    "pro.bannerCta": "Desbloquear Pro",
    "pro.socialProof": "Junte-se a mais de 500 atletas de BJJ treinando de forma mais inteligente",
    "pro.paymentIssueTitle": "Problema no pagamento \u2014 recursos Pro pausados",
    "pro.paymentIssueDesc": "Seu \u00faltimo pagamento falhou. Atualize suas informa\u00e7\u00f5es de cobran\u00e7a para continuar.",
    "pro.fixNow": "Corrigir agora",
    "pro.pastDueTitle": "Pagamento falhou",
    "pro.pastDueDesc": "Seu cart\u00e3o pode ter expirado ou tem saldo insuficiente. Atualize suas informa\u00e7\u00f5es de pagamento para manter o acesso Pro.",
    "pro.updateCard": "Atualizar cart\u00e3o",
    "pro.canceledTitle": "Plano Pro cancelado",
    "pro.canceledDesc": "Os recursos premium est\u00e3o desativados. Fa\u00e7a upgrade novamente para desbloquear todos os recursos.",
    "pro.rejoin": "Voltar",
    "pro.allFeaturesUnlocked": "Todos os recursos Pro desbloqueados",
    "pro.disclaimer": "Eu entendo que esta \u00e9 uma assinatura digital e concordo com os Termos de Servi\u00e7o. O BJJ App \u00e9 um registro de treino, n\u00e3o substitui instru\u00e7\u00e3o qualificada.",
    "pro.disclaimerAria": "Reconhecimento do aviso de assinatura",

    # === csv ===
    "csv.exportFailed": "Falha na exporta\u00e7\u00e3o",
    "csv.header.date": "Data",
    "csv.header.type": "Tipo",
    "csv.header.duration": "Dura\u00e7\u00e3o (min)",
    "csv.header.result": "Resultado",
    "csv.header.opponent": "Oponente",
    "csv.header.finish": "Finaliza\u00e7\u00e3o",
    "csv.header.event": "Evento",
    "csv.header.notes": "Observa\u00e7\u00f5es",
    "csv.header.techName": "Nome da T\u00e9cnica",
    "csv.header.category": "Categoria",
    "csv.header.mastery": "N\u00edvel de Dom\u00ednio",
    "csv.win": "Vit\u00f3ria",
    "csv.loss": "Derrota",
    "csv.draw": "Empate",
    "csv.button.training": "CSV",
    "csv.button.techniques": "CSV de T\u00e9cnicas",
    "csv.button.pdf": "PDF",
    "csv.locked": "CSV (Pro)",
    "csv.pdfTitle": "Registros de Treino",
    "csv.pdfSubtitle": "BJJ App \u2014 Registro de Treinos",
    "csv.pdfGenerated": "Gerado em",
    "csv.pdfTotalSessions": "Total de Sess\u00f5es",
    "csv.pdfTotalHours": "Total de Horas",
    "csv.pdfDateRange": "Per\u00edodo",
    "csv.pdfTo": "at\u00e9",
    "csv.pdfHours": "hrs",
    "csv.pdfSessions": "sess\u00f5es",
    "csv.pdfSummary": "Resumo",
    "csv.pdfNoData": "Nenhum registro de treino para exportar",
    "csv.pdfPrintHint": "Selecione \"Salvar como PDF\" para criar um arquivo PDF",

    # === report ===
    "report.title": "Relat\u00f3rio de Desempenho",
    "report.tabWeek": "Semana",
    "report.tabMonth": "M\u00eas",
    "report.sessions": "Sess\u00f5es",
    "report.totalTime": "Tempo Total",
    "report.avgTime": "M\u00e9dia/Sess\u00e3o",
    "report.minUnit": "min",
    "report.maxStreak": "Melhor Sequ\u00eancia",
    "report.streakValue": "{n} dias",
    "report.typeDistribution": "Distribui\u00e7\u00e3o por Tipo de Treino",
    "report.weeklyTrend": "Tend\u00eancia Semanal",
    "report.emptyState": "Registre pelo menos 2 semanas de treino para gerar seu relat\u00f3rio",
    "report.upgradeCta": "Desbloquear Relat\u00f3rio com Pro",
    "report.insightWeekUp": "Voc\u00ea treinou {n} vez(es) a mais que na semana passada!",
    "report.insightWeekDown": "Voc\u00ea treinou {n} vez(es) a menos que na semana passada. Continue firme!",
    "report.insightConsecutiveUp": "3 semanas de frequ\u00eancia crescente \u2014 \u00f3timo ritmo!",
    "report.insightLowDrilling": "Sua propor\u00e7\u00e3o de drill est\u00e1 baixa esta semana. Considere adicionar sess\u00f5es focadas em t\u00e9cnica.",
    "report.insightStreak": "Sua melhor sequ\u00eancia \u00e9 de {n} dias consecutivos \u2014 consist\u00eancia impressionante!",

    # === achievement ===
    "achievement.milestone.1.text": "Primeiro treino registrado!",
    "achievement.milestone.1.subtext": "Sua jornada no BJJ come\u00e7a!",
    "achievement.milestone.7.text": "7 sess\u00f5es alcan\u00e7adas!",
    "achievement.milestone.7.subtext": "Voc\u00ea est\u00e1 criando um h\u00e1bito!",
    "achievement.milestone.10.text": "10 sess\u00f5es alcan\u00e7adas!",
    "achievement.milestone.10.subtext": "O verdadeiro desafio come\u00e7a!",
    "achievement.milestone.30.text": "30 sess\u00f5es alcan\u00e7adas!",
    "achievement.milestone.30.subtext": "Um m\u00eas de dedica\u00e7\u00e3o!",
    "achievement.milestone.50.text": "50 sess\u00f5es alcan\u00e7adas!",
    "achievement.milestone.50.subtext": "O caminho para a Blue Belt est\u00e1 ao alcance!",
    "achievement.milestone.100.text": "100 sess\u00f5es!",
    "achievement.milestone.100.subtext": "Bem-vindo \u00e0 classe guerreira do BJJ!",
    "achievement.milestone.200.text": "200 sess\u00f5es alcan\u00e7adas!",
    "achievement.milestone.200.subtext": "O caminho da maestria est\u00e1 vis\u00edvel!",
    "achievement.milestone.365.text": "365 sess\u00f5es!",
    "achievement.milestone.365.subtext": "Um ano de dedica\u00e7\u00e3o! Verdadeira vida de BJJ!",
    "achievement.milestone.500.text": "500 sess\u00f5es alcan\u00e7adas!",
    "achievement.milestone.500.subtext": "Classe de conquista excepcional!",
    "achievement.milestone.1000.text": "1.000 sess\u00f5es alcan\u00e7adas!",
    "achievement.milestone.1000.subtext": "Comprometimento de lenda do BJJ!",
    "achievement.shareButton": "Compartilhar no X",
    "achievement.shareText": "Acabei de atingir {n} sess\u00f5es de treino no BJJ App! \U0001F94B {text} #BJJ #ConsistencyWins #BrazilianJiuJitsu",

    # === beltPromo ===
    "beltPromo.congrats": "Parab\u00e9ns! \U0001F389",
    "beltPromo.advanced": "Voc\u00ea avan\u00e7ou de {from} para {to}. Continue rolando!",
    "beltPromo.shareOnX": "Compartilhar no X",
    "beltPromo.ariaDialog": "Celebra\u00e7\u00e3o de promo\u00e7\u00e3o de faixa",
    "beltPromo.ariaShareX": "Compartilhar promo\u00e7\u00e3o de faixa no X (Twitter)",
    "beltPromo.oss": "OSS! \U0001F525 Continuar",
    "beltPromo.keepRolling": "Tire um print \u2014 este modal n\u00e3o vai fechar sozinho.",
    "beltPromo.screenshotHint": "Toque em OSS quando estiver pronto para continuar.",

    # === ageGate ===
    "ageGate.body": "O BJJ App coleta dados de treino. Pela lei dos EUA (COPPA), precisamos verificar que voc\u00ea tem 13 anos de idade ou mais antes de continuar.",
    "ageGate.confirm": "\u2705 Eu tenho 13 anos ou mais",
    "ageGate.deny": "Eu tenho menos de 13 anos",
    "ageGate.footer": "Exigido pela lei federal dos EUA \u00b7 bjj-app.net",
    "ageGate.blockedTitle": "Restri\u00e7\u00e3o de Idade",
    "ageGate.blockedBody": "O BJJ App \u00e9 projetado para usu\u00e1rios com 13 anos de idade ou mais. N\u00e3o podemos permitir acesso para usu\u00e1rios com menos de 13 anos (conformidade COPPA).",
    "ageGate.blockedContact": "Se voc\u00ea acredita que isso \u00e9 um erro, pe\u00e7a a um pai ou respons\u00e1vel para nos contatar em 307239t777@gmail.com",

    # === install ===
    "install.ios": "Adicione \u00e0 Tela Inicial para usar como app!",
    "install.iosInstructions": "Safari \u2192 Compartilhar \u2192 \"Adicionar \u00e0 Tela Inicial\"",
    "install.android": "Instale como app para usar offline!",
    "install.button": "Instalar",
    "install.installing": "Instalando...",
    "install.close": "Fechar banner",
    "install.error": "Instala\u00e7\u00e3o falhou. Por favor, tente novamente.",

    # === onboarding ===
    "onboarding.title": "Primeiros Passos",
    "onboarding.progress": "{done}/{total} completo",
    "onboarding.step.firstLog": "Registre sua primeira sess\u00e3o de treino",
    "onboarding.step.setGoal": "Defina sua meta semanal de treino",
    "onboarding.step.addTechnique": "Adicione uma t\u00e9cnica \u00e0 sua biblioteca",
    "onboarding.step.safetyAck": "Leia o aviso de seguran\u00e7a",
    "onboarding.safetyBanner": "\u26a0\ufe0f O BJJ envolve contato f\u00edsico e risco de les\u00e3o. Sempre treine sob supervis\u00e3o qualificada. Este app n\u00e3o substitui instru\u00e7\u00e3o profissional.",
    "onboarding.firstRollTitle": "Bem-vindo ao tatame! \U0001F94B",
    "onboarding.firstRollDesc": "Seu primeiro rola est\u00e1 registrado. A jornada come\u00e7ou.",
    "onboarding.firstRollCta": "Vamos rolar \U0001F91C",
    "onboarding.celebTitle": "Bem-vindo ao Tatame! \U0001F94B",
    "onboarding.celebSubtitle": "Configura\u00e7\u00e3o completa \u2014 agora v\u00e1 rolar!",

    # === freeze ===
    "freeze.title": "Streak Freeze",
    "freeze.protects": "Protege sua sequ\u00eancia em emerg\u00eancias",
    "freeze.used": "\u2744\ufe0f Streak Freeze usado! Sua sequ\u00eancia est\u00e1 salva.",
    "freeze.useFailed": "Falha ao usar. Por favor, tente novamente mais tarde.",
    "freeze.atRisk": "\U0001F525 Sequ\u00eancia de {n} dias em risco! Streak Freeze dispon\u00edvel",
    "freeze.noYesterday": "Nenhum treino registrado ontem. Use um freeze para proteger sua sequ\u00eancia.",
    "freeze.remaining": "{n} usos restantes",
    "freeze.recentUsage": "Uso recente:",
    "freeze.using": "Usando...",
    "freeze.useBtn": "\u2744\ufe0f Usar Freeze ({n} restante)",
    "freeze.zeroRemaining": "Streak Freeze: 0 restante",
    "freeze.getUnlimited": "Obtenha freezes ilimitados com Pro",
    "freeze.goPro": "Assinar Pro \u2192",
    "freeze.paywallTitle": "Proteja sua sequ\u00eancia de {n} dias",
    "freeze.paywallSubtitle": "Streak Freezes s\u00e3o um recurso Pro. Fa\u00e7a upgrade para obter prote\u00e7\u00e3o ilimitada.",
    "freeze.paywallPoint1": "Streak Freezes Ilimitados",
    "freeze.paywallPoint2": "Heatmap de treino e an\u00e1lises",
    "freeze.paywallPoint3": "Acompanhamento corporal e de les\u00f5es",
    "freeze.paywallPoint4": "An\u00e1lise de rolas (em breve)",
    "freeze.paywallCta": "Upgrade para Pro \u2014 $9,99/m\u00eas",
    "freeze.paywallDismiss": "Talvez depois",

    # === aiCoach ===
    "aiCoach.modeGeneral": "Semanal",
    "aiCoach.modeWeakness": "Pontos Fracos",
    "aiCoach.modeNextSession": "Pr\u00f3xima Sess\u00e3o",
    "aiCoach.modeCompPrep": "Prep Competi\u00e7\u00e3o",
    "aiCoach.section_challenge": "Desafio da Semana",
    "aiCoach.section_plan": "Plano de A\u00e7\u00e3o",
    "aiCoach.section_sparring": "Plano de Sparring",
    "aiCoach.section_week_before": "Semana Antes da Competi\u00e7\u00e3o",

    # === weightCut ===
    "weightCut.title": "Planejador de Corte de Peso",
    "weightCut.tolose": "A Perder",
    "weightCut.daysLeft": "Dias Restantes",
    "weightCut.daysUnit": "d",
    "weightCut.weeklyRate": "Taxa Semanal",
    "weightCut.weekUnit": "sem",
    "weightCut.aggressiveWarning": "Esta taxa de corte excede os limites seguros (>1kg/semana ou >10% do peso corporal). Considere estender seu prazo ou consultar um nutricionista esportivo.",
    "weightCut.phases": "Fases do Corte",
    "weightCut.phaseNormal": "Fase de Treino",
    "weightCut.phaseNormalAdvice": "Treine normalmente. Dieta limpa, leve d\u00e9ficit cal\u00f3rico. Foco na perda de peso sustent\u00e1vel.",
    "weightCut.phaseWaterLoad": "Carga de \u00c1gua",
    "weightCut.phaseWaterLoadAdvice": "Aumente a ingest\u00e3o de \u00e1gua para 6-8L/dia. Isso prepara seu corpo para eliminar \u00e1gua de forma eficiente depois.",
    "weightCut.phaseWaterCut": "Corte de \u00c1gua",
    "weightCut.phaseWaterCutAdvice": "Reduza gradualmente a ingest\u00e3o de \u00e1gua. Apenas treino leve. Monitore como voc\u00ea se sente de perto.",
    "weightCut.phaseWeighIn": "Dia da Pesagem",
    "weightCut.phaseWeighInAdvice": "Pese, depois reidrate imediatamente com eletr\u00f3litos e carboidratos leves.",
    "weightCut.milestones": "Metas Semanais",
    "weightCut.week": "Sem",
    "weightCut.alreadyAtTarget": "Voc\u00ea j\u00e1 est\u00e1 no peso alvo ou abaixo dele!",

    # === wiki ===
    "wiki.dailyTip": "Conhecimento BJJ de Hoje",
    "wiki.readMore": "Leia mais no Wiki",
    "wiki.close": "\u25b2 Fechar",
    "wiki.nextPreview": "Amanh\u00e3: {category} \u25bc",
    "wiki.nextHint": "Dica de amanh\u00e3",
    "wiki.peekAhead": "Pr\u00e9via \u2192",

    # === skillmap ===
    "skillmap.tabRoots": "Pontos de Entrada",
    "skillmap.tabAll": "Todas as T\u00e9cnicas",
    "skillmap.rootList": "Pontos de Entrada",
    "skillmap.emptyTitle": "Seu skill map est\u00e1 vazio",
    "skillmap.emptyBody": "Comece adicionando sua primeira t\u00e9cnica para construir seu mapa de BJJ.",
    "skillmap.emptyBodyPC": "Clique com o bot\u00e3o direito em qualquer lugar da tela para adicionar sua primeira t\u00e9cnica.",
    "skillmap.addFirstTechnique": "Adicionar primeira t\u00e9cnica",
    "skillmap.addTechniqueTitle": "Adicionar t\u00e9cnica",
    "skillmap.addSubTechnique": "Adicionar t\u00e9cnica conectada",
    "skillmap.namePlaceholder": "Nome da t\u00e9cnica",
    "skillmap.descPlaceholder": "Observa\u00e7\u00f5es (opcional)",
    "skillmap.addBtn": "Adicionar",
    "skillmap.connectExisting": "Conectar a t\u00e9cnica existente",
    "skillmap.connectTitle": "Conectar t\u00e9cnicas",
    "skillmap.connectFrom": "De",
    "skillmap.connectTarget": "Selecionar alvo",
    "skillmap.selectTarget": "\u2014 selecionar \u2014",
    "skillmap.edgeLabelPlaceholder": "R\u00f3tulo da conex\u00e3o (opcional)",
    "skillmap.connectBtn": "Conectar",
    "skillmap.leadsTo": "Leva a",
    "skillmap.noChildren": "Nenhuma conex\u00e3o ainda.",
    "skillmap.noRoots": "Nenhuma t\u00e9cnica de ponto de entrada ainda.",
    "skillmap.openNode": "Abrir",
    "skillmap.deleteNode": "Remover",
    "skillmap.deleteEdge": "Remover conex\u00e3o",
    "skillmap.proLockBtn": "Pro: Adicionar mais t\u00e9cnicas",
    "skillmap.proModalTitle": "Seu mapa est\u00e1 crescendo! \U0001F525",
    "skillmap.proModalBody": "Voc\u00ea adicionou 10 t\u00e9cnicas. Fa\u00e7a upgrade para Pro para continuar construindo.",
    "skillmap.proModalTitlePC": "Voc\u00ea construiu um mapa impressionante! \U0001F525",
    "skillmap.proModalBodyPC": "Fa\u00e7a upgrade para Pro para adicionar t\u00e9cnicas ilimitadas e desbloquear a sincroniza\u00e7\u00e3o com o Di\u00e1rio de T\u00e9cnicas.",
    "skillmap.upgradeBtn": "Upgrade para Pro \u2014 $9,99/m\u00eas",
    "skillmap.upgradeAriaLabel": "Upgrade para o plano Pro",
    "skillmap.maybeLater": "Talvez depois",
    "skillmap.addNodeSuccess": "T\u00e9cnica adicionada",
    "skillmap.addNodeError": "Falha ao adicionar t\u00e9cnica",
    "skillmap.addEdgeError": "Falha ao conectar t\u00e9cnicas",
    "skillmap.connectSuccess": "Conectado",
    "skillmap.deleteSuccess": "Exclu\u00eddo",
    "skillmap.cycleError": "Esta conex\u00e3o criaria um ciclo \u2014 n\u00e3o permitido",
    "skillmap.pcHint": "Clique direito para adicionar \u00b7 Arraste o n\u00f3 para mover \u00b7 Clique \u25cf para conectar",
    "skillmap.pcContextHint": "Clique direito ou tecla Tab para adicionar uma t\u00e9cnica",
    "skillmap.portHint": "Conectar a partir desta t\u00e9cnica",
    "skillmap.connectingHint": "Clique em outra t\u00e9cnica para conectar \u2192",
    "skillmap.resetView": "Resetar visualiza\u00e7\u00e3o",
    "skillmap.canvasShortcuts": "Atalhos de teclado da tela",
    "skillmap.magicOrganize": "Organizar Automaticamente",
    "skillmap.organizeSuccess": "Layout organizado \u2728",
    "skillmap.viewMode": "Visualizar",
    "skillmap.editMode": "Editar",
    "skillmap.drawerAddChild": "Adicionar T\u00e9cnica Filha",
    "skillmap.drawerAddChildHint": "Digite um nome para a t\u00e9cnica filha",
    "skillmap.drawerConnect": "Conectar a Existente",
    "skillmap.drawerRemove": "Remover N\u00f3",
    "skillmap.connectMobileHint": "Toque em uma t\u00e9cnica para conectar \u2192",
    "skillmap.deleteConfirmMsg": "Remover esta t\u00e9cnica e suas conex\u00f5es?",
    "skillmap.addNodeMobile": "Adicionar T\u00e9cnica",
    "skillmap.fullScreen": "Tela Cheia",
    "skillmap.exitFullScreen": "Sair da Tela Cheia",
    "skillmap.overLimitBanner": "Voc\u00ea excedeu o limite gratuito. Fa\u00e7a upgrade para Pro para continuar editando suas {count} t\u00e9cnicas.",
    "skillmap.overLimitUpgrade": "Upgrade para Pro",

    # === landing ===
    "landing.navLogin": "Entrar",
    "landing.navGetStarted": "Come\u00e7ar",
    "landing.heroBadge": "Gr\u00e1tis para come\u00e7ar",
    "landing.heroTitle1": "Prove seu crescimento no BJJ",
    "landing.heroTitle2": "com dados reais.",
    "landing.heroDesc": "Acompanhe sess\u00f5es, t\u00e9cnicas e sequ\u00eancias em um s\u00f3 lugar.\nCada dia que voc\u00ea registra \u00e9 um passo mais perto da pr\u00f3xima faixa.",
    "landing.heroCta": "Come\u00e7ar a Registrar Gr\u00e1tis",
    "landing.heroSeeApp": "Ver o app",
    "landing.heroSubtext": "Entre com GitHub ou Google. Sem cart\u00e3o de cr\u00e9dito.",
    "landing.heroGuest": "Experimentar sem cadastro \u2192",
    "landing.engTitle1": "Pare de esquecer o que aprendeu.",
    "landing.engTitle2": "Registre cada t\u00e9cnica.",
    "landing.engDesc": "Voc\u00ea treina um movimento. Esquece na semana seguinte.\nO BJJ App resolve isso \u2014 registre suas sess\u00f5es, salve t\u00e9cnicas com n\u00edveis de dom\u00ednio e mantenha sua sequ\u00eancia de treino viva.",
    "landing.engPillSession": "Registro de sess\u00e3o (Gi / NoGi / Drill)",
    "landing.engPillTechnique": "Caderno de t\u00e9cnicas",
    "landing.engPillStreak": "Sequ\u00eancia de treino",
    "landing.engPillGoals": "Metas semanais e mensais",
    "landing.engPillHeatmap": "Heatmap de calend\u00e1rio",
    "landing.engPillComp": "Registro de competi\u00e7\u00f5es V/D",
    "landing.engPillSkillMap": "Skill map visual",
    "landing.engCta": "Come\u00e7ar a Registrar Gr\u00e1tis",
    "landing.engGuest": "Experimentar sem cadastro",
    "landing.engSubtext": "Sem cart\u00e3o de cr\u00e9dito. Entre com GitHub ou Google. Leva 30 segundos.",
    "landing.proofBadge": "\u2705 Confiado por lutadores no mundo todo",
    "landing.proofTitle": "Dados reais de treino",
    "landing.proofSessions": "50.000+",
    "landing.proofSessionsLabel": "Sess\u00f5es registradas",
    "landing.proofTechniques": "1.200+",
    "landing.proofTechniquesLabel": "T\u00e9cnicas salvas",
    "landing.proofStreak": "30+",
    "landing.proofStreakLabel": "Maior sequ\u00eancia (dias)",
    "landing.proofFree": "Gr\u00e1tis",
    "landing.proofFreeLabel": "Todos os recursos principais",
    "landing.stepsTitle": "3 passos para progresso vis\u00edvel",
    "landing.step1Title": "Registre",
    "landing.step1Desc": "Registre cada sess\u00e3o. Data, dura\u00e7\u00e3o, tipo e notas em segundos. Funciona perfeitamente no celular.",
    "landing.step2Title": "Acompanhe",
    "landing.step2Desc": "Seu dashboard atualiza em tempo real. Sequ\u00eancia, progresso de metas e contagem de t\u00e9cnicas em um olhar.",
    "landing.step3Title": "Melhore",
    "landing.step3Desc": "Identifique suas \u00e1reas fracas e corrija-as. Dados provam seu progresso e mant\u00eam a motiva\u00e7\u00e3o alta.",
    "landing.previewTitle": "Veja como funciona",
    "landing.previewSubtitle": "Pronto para usar logo ap\u00f3s o cadastro. Recursos principais gr\u00e1tis para sempre.",
    "landing.featureLogTitle": "Registre cada sess\u00e3o",
    "landing.featureLogDesc": "Acompanhe Gi, NoGi, drill, competi\u00e7\u00e3o e open mat. Revise seu calend\u00e1rio a qualquer momento.",
    "landing.featureGoalsTitle": "Defina metas semanais e mensais",
    "landing.featureGoalsDesc": "Acompanhe seu objetivo com uma barra de progresso. Fica verde quando voc\u00ea atinge.",
    "landing.featureWeakTitle": "Identifique seus pontos fracos",
    "landing.featureWeakDesc": "Organize t\u00e9cnicas por posi\u00e7\u00e3o. Avalia\u00e7\u00f5es por estrelas mostram onde voc\u00ea precisa trabalhar.",
    "landing.featureStreakTitle": "Construa uma sequ\u00eancia",
    "landing.featureStreakDesc": "Conta automaticamente seus dias consecutivos de treino. Dif\u00edcil de deixar quebrar.",
    "landing.featureCalendarTitle": "Visualiza\u00e7\u00e3o em calend\u00e1rio",
    "landing.featureCalendarDesc": "Veja seus dias de treino em um calend\u00e1rio mensal com pontos coloridos por tipo.",
    "landing.featureSkillMapTitle": "Skill Map Visual",
    "landing.featureSkillMapDesc": "Construa um mapa mental das suas t\u00e9cnicas. Veja as conex\u00f5es entre posi\u00e7\u00f5es e submissions.",
    "landing.featureStartCta": "Comece a registrar seus dados",
    "landing.coreLogTitle": "Registro de Treino",
    "landing.coreLogDesc": "Registre data, dura\u00e7\u00e3o, tipo e notas. Totaliza automaticamente suas sess\u00f5es mensais e tempo de treino.",
    "landing.coreTechTitle": "Di\u00e1rio de T\u00e9cnicas",
    "landing.coreTechDesc": "Organize t\u00e9cnicas por posi\u00e7\u00e3o. Acompanhe n\u00edveis de dom\u00ednio para identificar e corrigir pontos fracos.",
    "landing.coreStreakTitle": "Sequ\u00eancia de Dias",
    "landing.coreStreakDesc": "Conta automaticamente seus dias consecutivos de treino. A sequ\u00eancia faz voc\u00ea voltar sempre.",
    "landing.coreSkillMapTitle": "Skill Map Visual",
    "landing.coreSkillMapDesc": "Mapeie suas t\u00e9cnicas. Visualize as conex\u00f5es entre posi\u00e7\u00f5es e submissions.",
    "landing.wikiTitle": "Aprofunde Seu Conhecimento em BJJ",
    "landing.wikiSubtitle": "4.000+ p\u00e1ginas de enciclop\u00e9dia gratuita de t\u00e9cnicas de BJJ \u2014 do iniciante ao avan\u00e7ado",
    "landing.wikiGuardTitle": "Sistemas de Guard",
    "landing.wikiGuardDesc": "Closed, Half, Spider, DLR",
    "landing.wikiLegTitle": "Leg Locks",
    "landing.wikiLegDesc": "Heel hooks, Ashi garami, Toe holds",
    "landing.wikiCompTitle": "Mentalidade de Competi\u00e7\u00e3o",
    "landing.wikiCompDesc": "Prepara\u00e7\u00e3o para luta, nervosismo, estrat\u00e9gia",
    "landing.wikiNutritionTitle": "Nutri\u00e7\u00e3o e Recupera\u00e7\u00e3o",
    "landing.wikiNutritionDesc": "Dieta para atletas de BJJ, preven\u00e7\u00e3o de les\u00f5es",
    "landing.wikiExplore": "Explorar o BJJ Wiki",
    "landing.faqTitle": "Perguntas Frequentes",
    "landing.faq1Q": "\u00c9 realmente gr\u00e1tis?",
    "landing.faq1A": "Sim, todos os recursos principais s\u00e3o completamente gratuitos. Registro de treino, di\u00e1rio de t\u00e9cnicas, acompanhamento de metas, calend\u00e1rio e gr\u00e1ficos s\u00e3o todos gratuitos. O plano Pro ($9,99/m\u00eas) desbloqueia Skill Map ilimitado, gr\u00e1ficos de 12 meses e streak freeze.",
    "landing.faq2Q": "\u00c9 bom para iniciantes?",
    "landing.faq2A": "Com certeza! White belts e blue belts s\u00e3o os usu\u00e1rios perfeitos. Feito para resolver dois problemas comuns: n\u00e3o lembrar nomes de t\u00e9cnicas e manter a consist\u00eancia. Registrar desde o primeiro dia torna o caminho para sua pr\u00f3xima faixa vis\u00edvel.",
    "landing.faq3Q": "Como \u00e9 diferente de um caderno?",
    "landing.faq3A": "Tr\u00eas diferen\u00e7as principais: (1) Contagem autom\u00e1tica de sequ\u00eancia \u2014 nunca perca o ritmo, (2) Gr\u00e1ficos visuais \u2014 veja seu crescimento em n\u00fameros, (3) Integra\u00e7\u00e3o com BJJ Wiki \u2014 consulte instantaneamente qualquer t\u00e9cnica de 4.000+ p\u00e1ginas. Dados provam seu progresso.",
    "landing.faq4Q": "Funciona no celular?",
    "landing.faq4A": "Sim! Totalmente responsivo e funciona perfeitamente no navegador do seu smartphone. Adicione \u00e0 tela inicial para usar como app nativo.",
    "landing.faq5Q": "Meus dados est\u00e3o seguros?",
    "landing.faq5A": "Os dados s\u00e3o armazenados com seguran\u00e7a no Supabase (PostgreSQL de n\u00edvel empresarial). Row Level Security significa que ningu\u00e9m pode acessar seus dados. Exporte tudo como CSV a qualquer momento \u2014 sem bloqueio.",
    "landing.finalCtaTitle": "Comece a Treinar de Forma Mais Inteligente Hoje",
    "landing.finalCtaSubtitle": "Sem cart\u00e3o de cr\u00e9dito. Cadastre-se com GitHub ou Google em segundos.",
    "landing.finalCtaButton": "Come\u00e7ar a Registrar Gr\u00e1tis",
    "landing.footerCopyright": "\u00a9 2026 BJJ App. Todos os direitos reservados.",
    "landing.footerTerms": "Termos de Servi\u00e7o",
    "landing.footerPrivacy": "Pol\u00edtica de Privacidade",
    "landing.footerTokushoho": "\u7279\u5b9a\u5546\u53d6\u5f15\u6cd5\u306b\u57fa\u3065\u304f\u8868\u8a18",

    # === gymLanding ===
    "gymLanding.navIndividuals": "Para Indiv\u00edduos",
    "gymLanding.navSignIn": "Entrar",
    "gymLanding.navDashboard": "Abrir Dashboard \u2192",
    "gymLanding.heroBadge": "Para Donos de Academia e Coaches",
    "gymLanding.heroTitle1": "Mantenha Seus Alunos",
    "gymLanding.heroTitle2": "Engajados Entre as Aulas",
    "gymLanding.heroDesc": "Dashboard de academia que acompanha quais alunos est\u00e3o treinando, envia atualiza\u00e7\u00f5es de curr\u00edculo e identifica alunos em risco de evas\u00e3o antes que saiam.",
    "gymLanding.heroCta": "Abrir Dashboard \u2014 Gr\u00e1tis \u2192",
    "gymLanding.heroWaitlist": "Ou entrar na lista de espera \u2192",
    "gymLanding.featuresTitle": "O Que Voc\u00ea Recebe",
    "gymLanding.feature1Title": "Dashboard de Risco de Evas\u00e3o",
    "gymLanding.feature1Desc": "Sinaliza automaticamente alunos que n\u00e3o registraram treino em 2+ semanas. Veja seus alunos em risco antes que desapare\u00e7am.",
    "gymLanding.feature1Point1": "Sistema de alerta em tempo real",
    "gymLanding.feature1Point2": "Contate alunos antes que seja tarde",
    "gymLanding.feature1Point3": "Reduza a evas\u00e3o em 20-30%",
    "gymLanding.feature2Title": "Envio Semanal de Curr\u00edculo",
    "gymLanding.feature2Desc": "Vincule a t\u00e9cnica da semana do BJJ Wiki. Todos os seus alunos veem no app. Estenda o aprendizado da aula para a prepara\u00e7\u00e3o em casa.",
    "gymLanding.feature2Point1": "Envie em 30 segundos",
    "gymLanding.feature2Point2": "4.000+ p\u00e1ginas gratuitas do BJJ Wiki dispon\u00edveis",
    "gymLanding.feature2Point3": "Aumente a reten\u00e7\u00e3o de alunos",
    "gymLanding.feature3Title": "Sistema de Convite por QR",
    "gymLanding.feature3Desc": "Gere um QR code \u00fanico para sua academia. Alunos escaneiam e entram automaticamente no seu grupo. Onboarding sem atrito.",
    "gymLanding.feature3Point1": "Imprima em panfletos e cartazes",
    "gymLanding.feature3Point2": "Compartilhe via email/WhatsApp",
    "gymLanding.feature3Point3": "Integra\u00e7\u00e3o instant\u00e2nea \u00e0 turma",
    "gymLanding.howTitle": "Como Funciona",
    "gymLanding.step1Title": "Alunos Baixam",
    "gymLanding.step1Desc": "Seus alunos acessam o BJJ App pela web (sem app store). Podem usar sozinhos ou entrar no grupo da sua academia.",
    "gymLanding.step2Title": "Escaneiam Seu QR",
    "gymLanding.step2Desc": "Eles escaneiam o QR code \u00fanico da sua academia. Conectados instantaneamente aos dados do seu gym. Sem formul\u00e1rios, sem atrito, pronto.",
    "gymLanding.step3Title": "Voc\u00ea Acompanha e Engaja",
    "gymLanding.step3Desc": "Veja quem est\u00e1 ativo, quem est\u00e1 sumindo, e envie atualiza\u00e7\u00f5es de curr\u00edculo. Alunos t\u00eam uma experi\u00eancia de pr\u00e1tica mais forte.",
    "gymLanding.pricingTitle": "Pre\u00e7os Simples",
    "gymLanding.pricingPopular": "Popular",
    "gymLanding.pricingStarter": "Starter",
    "gymLanding.pricingMonth": "m\u00eas",
    "gymLanding.pricingStarterLimit": "At\u00e9 50 alunos",
    "gymLanding.pricingStarterF1": "Dashboard de risco de evas\u00e3o",
    "gymLanding.pricingStarterF2": "Envio semanal de curr\u00edculo",
    "gymLanding.pricingStarterF3": "Sistema de convite por QR",
    "gymLanding.pricingStarterF4": "Suporte por email",
    "gymLanding.pricingPro": "Pro",
    "gymLanding.pricingProLimit": "Alunos ilimitados",
    "gymLanding.pricingProF1": "Tudo do Starter",
    "gymLanding.pricingProF2": "Grupos de alunos ilimitados",
    "gymLanding.pricingProF3": "An\u00e1lises avan\u00e7adas",
    "gymLanding.pricingProF4": "Suporte priorit\u00e1rio",
    "gymLanding.pricingCta": "Solicitar Acesso",
    "gymLanding.pricingNote": "\U0001F4E9 Envie-nos um email para planos personalizados. Teste gr\u00e1tis de 14 dias inclu\u00eddo.",
    "gymLanding.waitlistTitle": "Obtenha Acesso Antecipado",
    "gymLanding.waitlistDesc": "Os recursos para academias est\u00e3o em beta privado. Entre na lista de espera e entraremos em contato quando sua vaga estiver pronta.",
    "gymLanding.faqTitle": "D\u00favidas?",
    "gymLanding.faq1Q": "Os alunos precisam pagar?",
    "gymLanding.faq1A": "N\u00e3o. Alunos usam o BJJ App gratuitamente. Voc\u00ea paga pelos recursos de gest\u00e3o da academia. Alunos se beneficiam do curr\u00edculo e do pr\u00f3prio acompanhamento \u2014 sem custo para eles.",
    "gymLanding.faq2Q": "Tem taxa de configura\u00e7\u00e3o?",
    "gymLanding.faq2A": "Sem taxa de configura\u00e7\u00e3o. Sem contratos. Voc\u00ea pode cancelar a qualquer momento. Pegue seu QR code e comece a usar imediatamente ap\u00f3s o cadastro.",
    "gymLanding.faq3Q": "Posso usar com Stripe/PayPal para mensalidades?",
    "gymLanding.faq3A": "No momento, o app foca em engajamento e reten\u00e7\u00e3o. Estamos planejando integra\u00e7\u00e3o de pagamento para uma atualiza\u00e7\u00e3o futura. Por enquanto, use seu sistema de pagamento existente.",
    "gymLanding.faq4Q": "Preciso de habilidades t\u00e9cnicas?",
    "gymLanding.faq4A": "N\u00e3o. Tudo \u00e9 feito no navegador. Gere seu QR code, compartilhe com alunos, envie curr\u00edculo via link. \u00c9 isso.",
    "gymLanding.faq5Q": "E se os alunos pararem de usar o app?",
    "gymLanding.faq5A": "O dashboard mostra quem est\u00e1 ativo e quem n\u00e3o est\u00e1. Voc\u00ea perceber\u00e1 o desengajamento antes que os alunos saiam da sua academia. Esse \u00e9 o objetivo.",
    "gymLanding.finalCtaTitle": "Pronto para engajar seu time?",
    "gymLanding.finalCtaDesc": "Teste gr\u00e1tis de 14 dias. Sem cart\u00e3o de cr\u00e9dito. Cancele a qualquer momento.",
    "gymLanding.finalCtaButton": "Solicitar Demo \u2192",
    "gymLanding.footerCopyright": "\u00a9 2026 BJJ App. Feito por lutadores, para lutadores.",
    "gymLanding.footerTerms": "Termos",
    "gymLanding.footerPrivacy": "Privacidade",
    "gymLanding.footerTokushoho": "\u7279\u5b9a\u5546\u53d6\u5f15\u6cd5\u306b\u57fa\u3065\u304f\u8868\u8a18",

    # === gym ===
    "gym.atChurnRisk": "{n} alunos em risco de evas\u00e3o",
    "gym.upgradeToSee": "Fa\u00e7a upgrade para Gym Pro para ver quem \u2014 e entre em contato antes que desistam.",
    "gym.activeSection": "\U0001F7E2 Membros Ativos ({n})",
    "gym.slowingSection": "\U0001F7E1 Diminuindo ritmo ({n})",
    "gym.highRiskSection": "\U0001F534 Alto risco de evas\u00e3o ({n})",
    "gym.lastSeen": "Visto por \u00faltimo: {text}",
    "gym.sessionsPerMonth": "{n} sess\u00f5es/30d",
    "gym.detailsHidden": "\U0001F512 Detalhes ocultos \u2014",
    "gym.upgradeToSeeLink": "fa\u00e7a upgrade para ver",
    "gym.today": "Hoje",
    "gym.yesterday": "Ontem",
    "gym.daysAgo": "{n} dias atr\u00e1s",
    "gym.never": "Nunca",
    "gym.createError": "Falha ao criar academia. Por favor, tente novamente.",
    "gym.waitlistEmailLabel": "Seu email *",
    "gym.waitlistGymLabel": "Nome da Academia",
    "gym.waitlistEmailPlaceholder": "coach@suaacademia.com",
    "gym.waitlistGymPlaceholder": "Triangle BJJ Academy",
    "gym.waitlistJoining": "Entrando...",
    "gym.waitlistJoin": "Entrar na Lista de Espera \u2192",
    "gym.waitlistNoSpam": "Sem spam. Enviaremos um email quando os recursos para academias forem lan\u00e7ados.",
    "gym.waitlistSuccess": "Voc\u00ea est\u00e1 na lista!",
    "gym.waitlistSuccessDesc": "Entraremos em contato quando os recursos para academias estiverem prontos. Enquanto isso, incentive seus alunos a baixar o BJJ App \u2014 quanto mais entrarem, mais r\u00e1pido entramos em contato.",
    "gym.waitlistError": "Algo deu errado. Por favor, tente novamente.",
    "gym.waitlistNetworkError": "Erro de rede. Por favor, verifique sua conex\u00e3o.",
    "gym.currentGym": "\U0001F3EB Academia Atual",
    "gym.unknownGym": "Academia desconhecida",
    "gym.leaveGym": "Sair da academia",
    "gym.leaving": "Saindo...",
    "gym.leaveConfirmTitle": "Sair de {name}?",
    "gym.leaveConfirmDesc": "O dono da academia n\u00e3o ver\u00e1 mais seus dados de treino. Voc\u00ea pode voltar com um novo QR code.",
    "gym.membersLabel": "membros",
    "gym.totalSessions30d": "Total de sess\u00f5es (30d)",
    "gym.avgSessions30d": "M\u00e9dia de sess\u00f5es/membro",
    "gym.memberKicked": "Membro removido da academia.",
    "gym.kickFailed": "Falha ao remover membro. Por favor, tente novamente.",
    "gym.kickedBannerTitle": "Voc\u00ea foi removido da sua academia",
    "gym.kickedBannerDesc": "Voc\u00ea n\u00e3o \u00e9 mais membro da sua academia anterior. Voc\u00ea pode entrar em uma nova academia com um link de convite.",
    "gym.kickedBannerDismiss": "Entendi",
    "gym.rankingTitle": "Atividade de Treino",
    "gym.myRank": "Sua posi\u00e7\u00e3o: #{n}",
    "gym.rankingMe": "Voc\u00ea",
    "gym.rankingAnon": "Colega de treino",
    "gym.rankingFootnote": "Apenas membros que optaram \u00b7 Nomes ocultos por privacidade",
    "gym.rankingSessions": "Sess\u00f5es",
    "gym.rankingStreak": "Sequ\u00eancia",
    "gym.rankingStreakRestHint": "Dias de descanso previnem les\u00f5es \u2014 sequ\u00eancias s\u00e3o para divers\u00e3o, n\u00e3o press\u00e3o.",
    "gym.noMembersHint": "Membros aparecer\u00e3o aqui quando optarem por compartilhar seus dados de treino",
    "gym.rankingOptIn": "Participar do compartilhamento de atividade",
    "gym.rankingOptOut": "Sair do compartilhamento de atividade",
    "gym.rankingOptInHint": "Compartilhe suas estat\u00edsticas de treino com membros da academia",
    "gym.rankingOptOutHint": "Remover-se da visualiza\u00e7\u00e3o de atividade",
    "gym.rankingToggling": "Atualizando...",
    "gym.curriculumCardTitle": "\U0001F4DA Curr\u00edculo de Hoje da sua academia",
    "gym.curriculumCardCta": "Ver artigo \u2192",
    "gym.regenerateConfirm": "Regenerar c\u00f3digo de convite? Todos os QR codes e links existentes se tornar\u00e3o inv\u00e1lidos. Membros atuais n\u00e3o s\u00e3o afetados.",
    "gym.regenerating": "Regenerando...",
    "gym.regenerateBtn": "\U0001F504 Regenerar QR code (invalida links antigos)",
    "gym.removeMemberConfirm": "Tem certeza de que deseja remover {name} da sua academia?",
    "gym.removeMemberNote": "Eles ser\u00e3o notificados e podem voltar usando o QR code.",
    "gym.removeMemberBtn": "Remover membro",
    "gym.removeMemberTitle": "Remover da academia",
    "gym.sentToday": "Enviado hoje",
    "gym.sentYesterday": "Enviado ontem",
    "gym.sentDaysAgo": "Enviado {n} dias atr\u00e1s",
    "gym.curriculumPracticedBtn": "\u2610 Praticado",
    "gym.curriculumPracticedDone": "\u2611 Praticado!",
    "gym.ariaCopyInvite": "Copiar link de convite",
    "gym.ariaRegenerate": "Regenerar c\u00f3digo de convite (invalida QR codes antigos)",
    "gym.ariaUpgradePro": "Upgrade para Gym Pro",
    "gym.invalidInviteTitle": "Link de convite inv\u00e1lido",
    "gym.invalidInviteDesc": "Este link de convite da academia n\u00e3o \u00e9 mais v\u00e1lido ou expirou.",
    "gym.goToDashboard": "Ir para o dashboard",
    "gym.defaultOwnerName": "Dono da Academia",
    "gym.atChurnRisk1": "1 aluno em risco de evas\u00e3o",
    "gym.nudgeCopy": "Copiar lembrete",
    "gym.nudgeCopied": "Copiado!",
    "gym.nudgeTemplate": "Ei! Sentimos sua falta no tatame. Venha treinar com a gente logo! \U0001F94B",
    "gym.nudgeAriaLabel": "Copiar mensagem de lembrete para {name}",
    "gym.shareWhatsApp": "Compartilhar via WhatsApp",
    "gym.shareOther": "Compartilhar link",
    "gym.csvInstructions": "Cole os emails dos alunos abaixo \u2014 um por linha, ou CSV com uma coluna 'email'. Opcionalmente adicione uma coluna 'name'.",
    "gym.csvPlaceholder": "alice@example.com\nbob@example.com\n\nOU cole CSV:\nname,email\nAlice Smith,alice@example.com\nBob Jones,bob@example.com",
    "gym.csvResult": "{n} alunos encontrados",
    "gym.csvReset": "Recome\u00e7ar",
    "gym.csvNote": "Todos os alunos usam o mesmo link de convite \u2014 o c\u00f3digo de convite garante que eles entrem na sua academia.",

    # === gymJoin ===
    "gymJoin.title": "Entrar em {name}",
    "gymJoin.managedBy": "Gerenciado por: {owner}",
    "gymJoin.ownerCanSee": "O que o dono da academia pode ver:",
    "gymJoin.canSeeFrequency": "Sua frequ\u00eancia de treino (contagem de sess\u00f5es + datas apenas)",
    "gymJoin.canSeeBelt": "Sua gradua\u00e7\u00e3o de faixa",
    "gymJoin.cannotSeeNotes": "Suas notas de treino (sempre privadas)",
    "gymJoin.cannotSeeComp": "Seus detalhes de competi\u00e7\u00e3o (sempre privados)",
    "gymJoin.joining": "Entrando...",
    "gymJoin.joinAndShare": "Sim, entrar e compartilhar meus dados de treino",
    "gymJoin.joinNoShare": "Entrar sem compartilhar (usar o app apenas para mim)",
    "gymJoin.privacyNote": "Voc\u00ea pode alterar sua prefer\u00eancia de compartilhamento a qualquer momento em Configura\u00e7\u00f5es do Perfil. Sair da academia remove permanentemente seus dados do dashboard do dono.",
    "gymJoin.error": "Falha ao entrar na academia. Por favor, tente novamente.",
    "gymJoin.transferTitle": "Transferir de Academia?",
    "gymJoin.transferDesc": "Voc\u00ea est\u00e1 atualmente em outra academia. Entrar em {name} vai remov\u00ea-lo da sua academia atual, e o dono anterior n\u00e3o ver\u00e1 mais seus dados.",
    "gymJoin.transferYes": "Sim, transferir para {name}",
    "gymJoin.ariaAgeConfirm": "Confirma\u00e7\u00e3o de idade: Eu tenho 13 anos de idade ou mais",
    "gymJoin.ariaJoinShare": "Entrar na academia e compartilhar dados de treino",
    "gymJoin.ariaJoinNoShare": "Entrar na academia sem compartilhar dados",
}

translations.update(_t)

# Verify we have all filtered keys covered
missing = set(filtered_keys.keys()) - set(translations.keys())
if missing:
    print(f"WARNING: {len(missing)} keys not translated:")
    for k in sorted(missing):
        print(f"  - {k}")
else:
    print(f"All {len(translations)} keys translated successfully.")

# Write output
with open("/tmp/pt_batch3.json", "w", encoding="utf-8") as f:
    json.dump(translations, f, ensure_ascii=False, indent=2)

print(f"Output written to /tmp/pt_batch3.json")
